apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.0
          args: ["start", "--http-enabled=true"]
          ports:
            - name: http
              containerPort: 8080
            - name: jgroups
              containerPort: 7800
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secrets
          env:
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_PASSWORD
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: HOSTNAME
            - name: KC_CACHE
              value: "ispn"
            - name: KC_CACHE_STACK
              value: "dns"
            - name: JAVA_OPTS_APPEND
              value: >-
                -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
                -Djgroups.bind_addr=match-interface:eth0
                -Djgroups.join_timeout=10000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
