apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: keycloak
  labels:
    app: keycloak
spec:
  clusterIP: None
  ports:
    - name: jgroups
      port: 7800
      targetPort: 7800
  selector:
    app: keycloak
