apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/trusted-ips: "10.42.0.0/16,10.13.13.0/24"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/proxy-host: "true"
    traefik.ingress.kubernetes.io/proxy-proto: "true"
    traefik.ingress.kubernetes.io/proxy-port: "true"
spec:
  rules:
    - host: auth.loeffelmeister.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
