apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  routes:
    - match: Host(`auth.loeffelmeister.de`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
          sticky:
            cookie:
              name: AUTH_SESSION_ID
              secure: true
              httpOnly: true
