apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: samba-smb
  namespace: media
spec:
  entryPoints:
    - smb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: samba
          port: 445
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: samba-netbios
  namespace: media
spec:
  entryPoints:
    - netbios
  routes:
    - match: HostSNI(`*`)
      services:
        - name: samba
          port: 139
---
# UDP routes
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: samba-netbios-ns
  namespace: media
spec:
  entryPoints:
    - netbios-ns
  routes:
    - services:
        - name: samba
          port: 137
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: samba-netbios-dgm
  namespace: media
spec:
  entryPoints:
    - netbios-dgm
  routes:
    - services:
        - name: samba
          port: 138
