apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: media
spec:
  selector:
    app: samba
  ports:
  - name: netbios
    port: 139
    targetPort: 139
    protocol: TCP
  - name: smb
    port: 445
    targetPort: 445
    protocol: TCP
  type: ClusterIP
