---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook_url: AgC3GRtmFuMTk1qSU6n8L75/a3T1s+Z5aj4y8oCH8sK/5xHBx3xD1QxMfgDbr2lsv6GCHXDEUTu6QVFQ2ddAoQ4v6lDDx7YaQYEb/4uSNmDYi5Fm5RpnABeHMsw0KOXxe+RIyVouQrZg+0+L94JsNC8kGt0tY+y6UaTGpa7vU3pCAEKtVGUZXjScZzIazIdT9OmqbcMezpcjL44TRzqIMVvkegMA62+n1e9mx6aN4NETQXq7PuvA9dI9EcQwJjrWheD/ik43RcGVEHiErJfxoIf21ZIZ6McuBo5kBGreb3paXER0nKpgbpokSwZmKU2O6puOOtYxE/q4aAsyu383prtXfLiMsBb619O3yA2xPipysfJu6ohks1UL7NWrtl0E/r1gfWOOnBL+//wpMZH/aagogDNs2wwjWHK6YSwnwXuEJuCINR16HZB2OqCqo6VhzX6anyWY9A+Bp3wSaXsEImvcIpudRKwnyBIfezhHfgIGxYVoz9zkVeUo6LnGEqnp+VN0VNkcOGPfN+Oa39ndlOfXYwIeltNVR5RBLbox72C7fBOvdFBD0xjd0KTitxOUicOjcTNigjXrfnrYseKDDfNTrsdKJyqRN1432+50TFhxFAKCUfCvjSs1MzUmyjO4otv/hNcWcRL6WmszWGyl3UVNcn3s2l5v5uU6+meosWvT1buJ16TeS2qdMwMvs8q/B1QVxUuaY7qr4khlhMM84MPEh7DASzOXk6kymx1kSAbly4yYWv5DMq5Vg07VFB+tBOAq0T4tSdCZPvder+dHk6RyFq+sZeQ91XqPSC97wkZAD85dJ6S04awJZyiXHfehKek5L1sR79Ty/HZJahEamE208Lp2BsLYHy8/
  template:
    metadata:
      name: discord-webhook
      namespace: monitoring
    type: Opaque
