apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  routes:
    - match: Host(`grafana.loeffelmeister.de`)
      kind: Rule
      services:
        - name: monitoring-release-grafana
          port: 80
