apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: v71.2.0
  interval: 1m0s
  values:
    namespaceOverride: "monitoring"

    ## Provide custom recording or alerting rules to be deployed into the cluster.
    ##
    additionalPrometheusRulesMap: {}
    #  rule-name:
    #    groups:
    #    - name: my_group
    #      rules:
    #      - record: my_record
    #        expr: 100 * my_record

    ## Configuration for alertmanager
    ## ref: https://prometheus.io/docs/alerting/alertmanager/
    ##
    alertmanager:
      enabled: true
      ## @param alertmanager.enableFeatures Enable access to Alertmanager disabled features.
      ##
      enableFeatures: []

      ## Alertmanager configuration directives
      ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
      ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
      ##
      config:
        global:
          resolve_timeout: 5m
        inhibit_rules:
          - source_matchers:
              - "severity = critical"
            target_matchers:
              - "severity =~ warning|info"
            equal:
              - "namespace"
              - "alertname"
          - source_matchers:
              - "severity = warning"
            target_matchers:
              - "severity = info"
            equal:
              - "namespace"
              - "alertname"
          - source_matchers:
              - "alertname = InfoInhibitor"
            target_matchers:
              - "severity = info"
            equal:
              - "namespace"
          - target_matchers:
              - "alertname = InfoInhibitor"
        route:
          group_by: ["alertname", "cluster", "service"]
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 1h
          receiver: "discord"
          routes:
            - receiver: "null"
              matchers:
                - alertname = "Watchdog"
            - receiver: "discord-critical"
              matchers:
                - severity = "critical"
        receivers:
          - name: "null"
          - name: "discord"
            webhook_configs:
              - url_file: /etc/alertmanager/secrets/discord-webhook/webhook_url
                send_resolved: true
                http_config:
                  follow_redirects: true
                # Discord webhook format
                title: "🚨 Homelab Alert"
                text: |
                  {
                    "content": "**Alert**: {{ .GroupLabels.alertname }}\n**Severity**: {{ .CommonLabels.severity }}\n**Instance**: {{ .CommonLabels.instance }}\n**Summary**: {{ .CommonAnnotations.summary }}\n**Description**: {{ .CommonAnnotations.description }}"
                  }
          - name: "discord-critical"
            webhook_configs:
              - url_file: /etc/alertmanager/secrets/discord-webhook/webhook_url
                send_resolved: true
                http_config:
                  follow_redirects: true
                # Discord webhook format
                title: "🔥 CRITICAL: Homelab Alert"
                text: |
                  {
                    "content": "@everyone **CRITICAL ALERT**\n**Alert**: {{ .GroupLabels.alertname }}\n**Instance**: {{ .CommonLabels.instance }}\n**Summary**: {{ .CommonAnnotations.summary }}\n**Description**: {{ .CommonAnnotations.description }}"
                  }
        templates:
          - "/etc/alertmanager/config/*.tmpl"

      ## Storage for AlertManager
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
        secrets:
          - discord-webhook
        containers:
          - name: alertmanager
            env:
              - name: DISCORD_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: discord-webhook
                    key: webhook_url

    ## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
    ##
    grafana:
      enabled: true
      admin:
        existingSecret: grafana-admin
        userKey: username
        passwordKey: password

      envFromSecret: grafan-auth
      env:
        GF_SERVER_ROOT_URL: https://grafana.loeffelmeister.de
      # To make Grafana persistent (Using Statefulset)
      persistence:
        enabled: true
        type: sts
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        finalizers:
          - kubernetes.io/pvc-protection

    kubeApiServer:
      enabled: true
    ## Component scraping etcd
    ##
    kubeEtcd:
      enabled: false

    ## Component scraping kube proxy
    ##
    kubeProxy:
      enabled: false

    ## Deploy a Prometheus instance
    ##
    prometheus:
      enabled: true
      ## Settings affecting prometheusSpec
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#prometheusspec
      ##
      prometheusSpec:
        ## Prometheus StorageSpec for persistent data
        ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/platform/storage.md
        ##
        storageSpec:
          # Using PersistentVolumeClaim
          #
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
