apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.12.3
        ports:
        - containerPort: 7700
        env:
        - name: MEILI_HOST
          value: "http://meilisearch:7700"
        - name: MEILI_NO_ANALYTICS
          value: "true"
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: MEILI_MASTER_KEY
        volumeMounts:
        - name: meilisearch-data
          mountPath: /meili_data
      volumes:
      - name: meilisearch-data
        persistentVolumeClaim:
          claimName: meilisearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: librechat
spec:
  selector:
    app: meilisearch
  ports:
  - port: 7700
    targetPort: 7700