apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: librechat
spec:
  selector:
    app: rag-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
