repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: kustomize-validation
        name: Kustomize validation
        entry: bash -c 'kubectl kustomize ./k8s | kubectl apply --dry-run=client -f -'
        language: system
        pass_filenames: false
        files: ^k8s/.*$
