# echo-headers.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-headers
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-headers
  template:
    metadata:
      labels:
        app: echo-headers
    spec:
      containers:
        - name: echo-headers
          image: mendhak/http-https-echo:29
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-headers
  namespace: echo
spec:
  selector:
    app: echo-headers
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-headers
  namespace: echo
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # Same annotations as your Keycloak ingress
    traefik.ingress.kubernetes.io/trusted-ips: "10.42.0.0/16,10.13.13.0/24"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/proxy-host: "true"
    traefik.ingress.kubernetes.io/proxy-proto: "true"
    traefik.ingress.kubernetes.io/proxy-port: "true"
spec:
  rules:
    - host: headerecho.loeffelmeister.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-headers
                port:
                  number: 8080
