apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prownlarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prownlarr.lffl.internal`)
      kind: Rule
      services:
        - name: prownlarr
          port: 9696
  tls:
    secretName: kube-system/self-signed-cert
