---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-exporter-credentials
  namespace: media
spec:
  encryptedData:
    password: AgCUlBO9NQfm/2fNV1KLP9K6gn+txSImBbjkNMxq7KN3bnmNhmZDE303MkBdJeO/hoAEmsm+x79afrsqTbycJ3Z+Wj1DWuEEtkyuc18rg8dwVQ7RijkTghECnkzV7SyEOtQMAIBZxc4qmSh81mAG4KlfzfruZyuDRRh82N83/tZeqD9hi6ROa5M80mikLejTFV8/r6FPR4YeRBFcLAWMcfM1ULoHQ0FTs68EOwcy+sJbnOj6zr9wDUCEYZLNYfOtj6nBpST4W6sX/FpOeV+bK2ZL4sE9gurh4t38+XBKfLtuGykOkr+tlZI7sUujXfNoGvx8wY8cVhi+a4agPPd8NTLLkyp7MfwIRLvfOsMGuuZ0wUyvj6WwBvp5ghHICa6sLziSjPeXA5qjyxFN4cPoizxmxVJbX63YVxDsH7KkJd581NPjJD/exfjlH6yMidsGE3Ba2SeblSYKapw6VUVWD6kstjfOYgwiwaN1IHlCIftZX82+EhuowBmhX4GyXgHmhAyCQJU5qMKhSnlJnVFlyuR7GeGNt4zY+F7UxJcNFrBqZqUh3xazGtvkFcJZqObzoaUoSSBOTSNemKH94LVb21teXLL34gH74jWk4XvAVrynglj6bHYP549GmYD3QttSUmvdZLV+xifqACaP7+0FKz7s+7G8hsO1+4kNR/TI1tFcn5QEOfddElECuvPpWv0bWzK4QqM3KqlBD5SqqKUwIw==
    username: AgBxizlx/TrSAEFhyPh+fuusoiOx3+PH35biNIEVJCeHBbAPLZKFM7z6vFyDnhXfUIKTROYC1Buo0HPndml44tVhhUkokfy/dTHLJaRhDMMRHK0eKkmX/h0CejIpRDYgDOUPNfaj5p9yE6jPcRwdL2VhZ/jTv1Mq2jdaQq1ouoXOw4TSLi2mBjVbNKz/S4YwrA6rz5vzGwac2lYwZMabJKs8439/w2+ktlvLaX5KMPWXx6tUpSkVJuc9o0lYrrTWOax4Y4tuCw1ec5MhjLl8GIWUM4gJMJlD+JAFid0+bqZ3YoA5PfJ/TzTXcrtSSk4e281tRX/o+gHPqGQG2L4mRr+Cf4+8sBK0vBi8rAYP08u1PHfvwzXfNg2L/A1qiQ/aT6kewLSAwEt/oPQfW9TBFPhvtsy1kACIAk9vQVbuUsLUNNxHBgoPgreJDaQ70jRPWQLOMBtem+4cRqcHd2QlrEwaJ1HKcSO4XzgNYNzkswBJzWnn+kddG9KP8d/5SFftzw5t+tefivEVDpLnXB7r4Q2nasV1afXfOSE50gU/Q9O3sEiI89ugJuMjTet7nnM+3mHKBVmAQUASsSZUZEY/2nNsFeYWHl3j66gAkAcEBeX+dJmVWUR9H+Z3q6f6lq85piLR48f/VQT1KhUooa40U0qV5h5obB4ET5pAQKARR+jkzKwWWwHVMZVohn6rVQIpGBXAYnpkXA==
  template:
    metadata:
      name: qbittorrent-exporter-credentials
      namespace: media
    type: Opaque
