apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-exporter-metrics
  namespace: media
  labels:
    app: qbittorrent-exporter
    release: monitoring-release
spec:
  selector:
    matchLabels:
      app: qbittorrent-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
