apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-exporter
  namespace: media
  labels:
    app: qbittorrent-exporter
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: metrics
  selector:
    app: qbittorrent-exporter
