apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  namespace: media
spec:
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      labels:
        app: unpackerr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - homeserver-2
      containers:
        - name: unpackerr
          image: golift/unpackerr
          securityContext:
            runAsUser: 911
            runAsGroup: 911
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: UN_LOG_FILE
              value: "/downloads/unpackerr.log"
            - name: UN_SONARR_0_URL
              value: "http://sonarr.media.svc.cluster.local:8989"
            - name: UN_SONARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secrets
                  key: sonarr-api-key
            - name: UN_RADARR_0_URL
              value: "http://radarr.media.svc.cluster.local:7878"
            - name: UN_RADARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secrets
                  key: radarr-api-key
          volumeMounts:
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: media-data
      restartPolicy: Always
