---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpackerr-secrets
  namespace: media
spec:
  encryptedData:
    radarr-api-key: AgBUbDTXXeQSfjGMOwMMjc4N2/eAq7OWupSxQxbdUsEPc3tYAm0owbUJ629rEmD6M2SfS7ZIXdV/eWgbnazfThnEINMTQDCxtsC9ZedmXc2AdP+RW2zgR8egIfWsWSVOHsyFoc04rtQr+Wzie1irzOn340n3BZl8rXElzrHoijoa/Xet8AdxMeK6LCZ1xzmTz4VPAcz9XcUSSJbUg8K+mVsgOWNjXsI7OncZ58BpTiFJyP9AJO3dBipi+Uxf/WGdoe0RdoyInJDx8G5CiAsq46FnPjclTj2VbHHkCmSprzHmE0znIYDrr6H2Hcb2+5tVey07qy0g2BLBN1xBnLkQoA2c7Vz4XvI2kCv3iiFVBhRSbWqwBCSQcLoux2HVU9xuloEIypAVnbJDWs0eoT5eYlWF5Fj8vxoC0mz+JSWbDzedtPE6itSDZLw2Trugm2I8eWBO8fdz6EMmk8Pb+do15+BID75APK3hrkBjfyTppIHYZPH45t/tCxX6jdZcfGU9IN1l1yw6xk0eFEkMCAboIsVD+z0DT7hR5p38BUNXW0BBYGlugxlaRu0bDsHxKSDojxOAtbxLSiwq8yM1tcimkji9Ad6xpaVJc20lBlJssZcobKnY/M9WdoY1L27JAu42qf5fhy20bFU+OuDSBbs+p3r245jZLsEwyi26sRMV0MtJvqp/qylZeX47bHjQkVhsaJbo48hgL0DnB/6ffj0thsaPViM6CjounvbiIFCUBuUw9g==
    sonarr-api-key: AgBG36rVmFQG7tnjcue72U07DQ69xNcNQFaR8v6gnaMof4yuu7O7SfpCpj2TwO+zJSYDwIsYKT6jWcBCVCcWKbZULkWhlMkLTSGOfMR2TZrVhpuaapkuPpZofoqXN9lSxBb6x4Cnf6sTx1YYgFp9yXn4bOqCVMGslpE/n8MvaOlRt6DRiZIs05QwTnodqRc1hFJWngln055Z5X0tjbCQnU2kQfyzvhBXqZfogU00gc8AdIay6CCDAdguCubIbwXKvsM3IgRNXIqtX//yHSW2ppdEny266vyrT7X85HcBQ1WV0kIKwjJ4FtHtuVN+hrglUXUpZPH3PwXh1l6i997tnacI/B0kssp7uTAnak2GU7+oczvKQaUi2HNpHJI9/pyvomZ81654Xpnj9BUfLebiq8xOvJoSwg7ugX1Hd40MDz0In209QKKgFP6AqMre6RFTTX/91zuSQpddGgNvQWNsBUEsnhh+dr3qtgOlWY2wM2WnHcr7D+TmARSwVDAChBAIyljYUfPEomY45JFokb3Vbr/TqtnrPfH3V7fNV7HngXFX8Sy2ySx1BLj+/fMdnrmyp8OWmvPJNW62/CVfjFkGHeYSLxg/RJE0/ZXLh3wcCnBsD2RYGX8XHVTQoir6v3YKItaL48ANPFrmSLZNIccF/c6HKwBenBke04N9J8I10FK9h/RAjk2J3SDLNeAlbH7jMkktHsqIYj76SQ9zf0xfoYV2dtr4zWakirnwPKA9r6i+lQ==
  template:
    metadata:
      name: unpackerr-secrets
      namespace: media
    type: Opaque
