---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgB/cLkMrHVNuzJvp2cjQSQXwFLq+gau6YkQS5+S7xFWpKYivA2Sgpr8mztWdIdWI/k/413H23yLDD33QM3xML6DfZwaORrK3kSqTGrccZOy4ECSmcadGFv1LPaTGzmmPRPRG+P1uUxU8IFGUyOmPKi8lfA9BJKLPB6aLVGSWlCK65lEu4VIUoG6xwJDO5sFzUoBrGW0c2BHTKCCJhacAI9K1hoGR42NLiBWckqsPRA4aG9DZeJyoH9/88JHo3iYxm9qO79AzVk6Z/C8dAhH7Md0a/f7WtXPrfd8bqlvHWDzRkvlqvqIwsD5/kkNoTr6SCYe45o4hSOR94eqgpRhj9p5yORHHiP8AQ3rhps/HE0YzicBGKr3laIbc/vj0naf7ySM/hRIaHXjo6gZ5RxtcFcqWE5vGt1YewzY3RhT3L5mv00LH1EQCsjUkaXjJtqWmhE4cE17pmpb2gcFD8XJ457Tbzy6rA+IP5U32shj6kHkS/wp36lWbNamgB/IO0d+/p6LLfUGeEuIS+ZCpn638b7UxJZW/sDpEuEfZmCXn21gqeA7GRT79jvpcctZtEsNjA+ot8AsNKP/DPGuyPjmTpuHGkOqLfW4uA/BKNDRSYUeA0IEK/IizonaGWFbftsrrLt67KQ7KkW5ZBp3QUSsTqkYcESGOPSaMy2BjxIlOFl4S9iF8uPunN7oG7JNoXwZhAW7RM42SDzJGq9CPycaT6oxXBqqog==
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secrets
      namespace: searxng
    type: Opaque
