---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: namecheap-creds
  namespace: default
spec:
  encryptedData:
    login: AgBAnzx/5DNsTt8tubJ2VFcmVn3fpzHikRaS5IOYgVbTzGAHusqvo5RlmZWGPcSVn2+WGL90Llgf6kZIQ4Sbj26cqnae1y5p6dGuDpYIiT8S8b5dJRK0e33ZkFONA7baFhKoz4h1eC1ZNy8XrFsL1TNam7ajSvKxFJdWYXkPTXTwpgZP2pSMrPZosDLg6LONC7TnHYdxb7Trl+OtPIludbpVB3ViSuiA9l2J29mm3dDgGJN0B/sL3nGvk5KeZ6dDSJVvmc79MU9DaZTt+VcLOkmgHEGmXYiuwUiRC9HKF3OzqBPvAC4yEasD1XtCPIWuMiZHiGAMZq3Tc++e7Zv5NkvysgZro/VH9UlstplpmnXab3tBQlwUYpqPrq9otU6tv/8kf9lF1jD73bkNTUYtZDWVBOjcryOV9Fp54TQ+oHuQaSw28m4/Q9FVLZpVSeHe00aRvTerfq/6wkBUMq/gFLE+U/tdaV11lGY4zhSesS8YqVvkWm4nJBx15xQbD//BPwIjFO99lcjP4Rg5uN4nJfG8tfxa4WNVDL8w8R6LwOAwUyD4kND03P8Zz/6tdEN68VbioBue+IKA3Mqclfu32h07ZFEkCOLS6nqhQ5bBzvYjQuvnRRJ6dHJh0hxm5Phw3WjS3QsOt6WWGt1jL3GjdkJwtrSOeMUTcFKMHgqGNjkxCriBgO6Pf1IM4XIiTbvT0MhUJ4vt59sejR1ipcotug==
    password: AgDC+gSQkCabSETzmFkF+iaWdG2q+bOrxSHOH+7Ta1Qqa4X3p3tq7kavS+37VFISwFb1PxTGuOS8cl2fzfrTrXuJLLNwz7+CDNnTyR7GVeLk8HZDsDJAxH9mRO+4IkSnxeuqQ9tw1NgrQitFUbHF38v3d7cSulm1VP12CxzRAhiUSGJS5IkOG70IYJxnXm7l86siFk0eJW5ny/O2w6G1M/P0CqO9pn+Q/L6c0zNts7nKVr0F9QiHE08ss5I3aKezvJIc/NcdUdA3KoXKksxBLV7fECALdUXtBRRCqo7fmomWfaFKXS9lXSaT5dHU3tRAvX8ZqkW2E0+lyPUwS7Oi+pmfjj3G55cfhiPqMWsLlTSvqVCb/75XJxQNYr6vZS2w0SF0IrbjMzwavGSUNMsQzmLOQNFqUJsm3jcCAvsMvjHbK955z89nzx96J10EOeycfwyS1KpDXdomXjyOOEo9pQbIV+lzA7xSwxzBhSzbX4JrOMcm6lkFMwiG4nwGLZo51BFuU6EYZRK52j39xrufpciG5pVQoRkLe5LOqyRJjXDbm5FqJG29VEq6wQn/f86GthDp3QSxbzPDHD/F0VAGP8de6wlUMplkV9gqD8zU2SK+ab66Da7l0uCvSQQYVnSB1ne4jiLpZQnrr0a1kKt92/qEQJOosGiP/3+Nn4JyXHU34DybFmZXrSV03liZUrsGmCwulo4vX0gFJlSquLBoRw0=
  template:
    metadata:
      creationTimestamp: null
      name: namecheap-creds
      namespace: default
