---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: namecheap-creds
  namespace: homecloud
spec:
  encryptedData:
    password: AgB9DyDD5I6UFJnvV79aM/4TAvpxRso09Cg6lO2pEIPWsVKaeccxxJcQcX11ZgJJnuPzaYL6PCZfB6J3ooalWGlprhFs7chCK6m0qzYy8Nm+hNwI6o6Hn9AkKC9irlqCi27LSlsIijzTeVdiACNs0lKbbvwYa1trSN/Mlc5ZmyYLaL3ZLNF2zB2iAmJA6He5KDageKJKm92xiE7a62zjxU8JZ2Zw4cDL7XuazYV0i5My0ABVVkcXAknVu5+AA0eq/cedxxvFnKwZISgLZFmb4Hb368FfARjqtmc27F+p1kV7apH6T/aZYt5tuw/O+Q+TyyxLs0ar7DexJ+7GCTyQlG7EZBNxwaOaslEXuBBY0hSJnfU7NKjHVxz1gpQglhhPtvBaObu97WexND06FVm1wy4khmfMN5gL54ijwxnc2EMcvczZ27VEffPGAeyTDKhGrpK193otoAi8tcqOFLis7S94tL7ScD85UyIqZt30HkERyXaE41u/y8l4nn00IFPhJ8GlzlErL5suBWn4nkkUi3H59sCJzQeBNsMhryXcGuktMpv0YRnQKb7jE8+E++q/DYqr3tZOjalUzFFL5hgMeoP66yF0wwxFIQTzdXPacgICvKhAxYl+9iXXPSkBKxEQRLWHOZOa27nqPf6q3Onx2Su95NnJrSWRerCq9f1VUv9ad0HGEqC6k4vWLaHKR3THWmF1oj7GXMOjc/ubME5ySY6ADV1pKW3xxiEQbH6vvk6H+g==
  template:
    metadata:
      creationTimestamp: null
      name: namecheap-creds
      namespace: homecloud
    type: Opaque
