---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-admin-login
  namespace: paperless
spec:
  encryptedData:
    password: AgAsvKWI4V8D7sV4qUPl6uX8pDTBeUqmRFKfU7iHPgaWDIBxcQHwbXQ4T7OIRXJMhZ/4FN/cUKNV4IHyMEcsX/Yc3+nbUPeRkGuTvxKsJ5f7kW2t2BrV/Q15Uv5Ggqcu8tCGnuP1E1noO2OWXSf+Rx5pSquF4mTZDKP3tsCwHgIB+eN+wWfbsFxgfJWip4pz/S6kLclEoCatrzPVbhuue8r2bPFgP3Es9BCjHNGtdpMyhzZKB4Q1YMbatnBPGHtc+f1Z2Uy1xpV18PmO+yM0aSjYzXBo5Zluk0ZvGsT7WT9rAI8Qufrk0AnRP5ToCC7Kdv2IBcj0icVseVt/rsCfwVWrZ6IJUUoifTwIOc8TqyLXa8Vxbup8Awqr4OCdTbB3WmOuURVmAjqU4rS30sDeiRg3bAw+cnNgx0esDqjfCLNPBr408E2KAZC7Sgc7of7UeXs4jjwqdeXxED4gf3DaaQpEjoXbp1tWdge9fmqNhCK6Bx70uZvQ8fd/5I1Vgg72XgVtW0HLEByzPYex7gomyf58gQbKH8JiW3N7//5YZdJjEwquLsWDTouv+8oJPBGdCgncIpz8jriLAWgnT3LrOFrZTef2tLVFARiB3/ZcV1GuggrQAMEx5eF2rXCVyaZsXTsFloq7IdaZZlE4RMaGztn8uSBZ5HyfoFLOK94TVSLgjccIg5Yt3aKg7M8aWfGyWBZBmvjZJi3uUIcxr9Evrw==
    username: AgBMrhD36DGs8ufLQg5ZI//pI0vUkVfp2MTKRfmD/wwrtCy5QOcKfuKiwPgE8UGabHYNQAkPErJxQxFCBodjYpmNLIOl/dirVrEBYf1kJx3K42PSH1zYyiaKEBhMH171WATeb5ZSLlAG7i0NA8AJZGWedCiinqMiYTRWIWYjMjuhPsYeuoqVO+UXfYzMGbmBnfO8BQ8JR5KN/d4oYqKEi0Dg4zwYaCh1wL2ySLqlXGCixGojelb8ZVH29gBR8DVe6hKIZGyq0ZMabrKdUHEedFMY33ZRzTSIE3GSLUnSaYiEFpyPo8av67Dd9FGh3bZDPKS7Olrt7K62VV8XhdC3A8qSSwnBy2YGhqb0k9JrKoFgOzpLNeTfeeRmAsujLMJGmp4aHxkDUNZGb4rTAC1/5eJa9v4p9CcgXLMy9dTrAiOqytzwh4/AKNSsePAWcs2TZeBl1uXXERV/F8eBEPPbeK+im6jQApJGXs+m+ZNSKEwprqR5Y3o6tvvbYOUWhmZt1UMW7s7b9AEtpkUvQu4VIe1uuTSTnvRtWlkjYVaeMgPR4zCnTfNnZQjICNNRBEiDwS28Ezt0yPpk2RM1aKoOkuVVuEcv9SmRo9oJIyutRzTXtK1r2niSKDKW34h+QlI5AHk4gJRdY/ndwTIPThSMe19dLI1XB5tbP1avi7361Sl6gmk9AFV5DgJDiplbq+V6l/Et9iK2Dw/7
  template:
    metadata:
      creationTimestamp: null
      name: paperless-admin-login
      namespace: paperless
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-oidc
  namespace: paperless
spec:
  encryptedData:
    allauth-config: AgBqAr8uKGQQHw0gfVwOauybAG+spt+Q2okZ+6V8ZHCRnD+LXUJ2zE7rF+o2mmQql7VQ1jWHowvmU3IS6rZd3o8fHS6v6/IC8Ieswe7OfxiPYE04dbF/ZOeTKdx6KLrMhr+9IXiPVqgmub5oYYnOn6Bg+iC6UKzgWdLvPiSxc8gSyYgc3D9F0OyXWmqcN6ncwHYvksxycTuwH+1KwAGQ9WZQ3TdpDKTQ+PZfjwRWyUMaUu/y2brUx8rB0Ei77QtTARorsLDzdmZ1DNtxaK5ONWmq5IbByUOsjMPgh8nBW/O4s55i0EEb7wwB9YfxjxJRu342iaFGOINMOYuMxHOL/tGSdTOQOO3T0bvPsdzqpR2GKEkOOgIs2JUx8ay5UJb8lNP5qixtXcWKWOA1iU8H8LhXBYXoxNkOhHO5S81y0Oe9WXf1iqeCj1LTfKS3S40aUTriLKj0wqak36dMv4eSfpCaP9v9BFjc/+9f0PBvk+7gvzaw5e0cpQLiKMgdwOCKWwznZymjVEdMdRGU+Ib7BzCLtEFJ+SIEDVMBfLMhhW08vXYVIBmN9O4UkTBve5y1zkyPVGqHzEuoGBRbEk6avbHdWc+Uw1ClfTxawmw6WaqYHiOpXa+2ud0MuTve+kXuixqQI4KRwOY/XxRf1E8ZL6lvgmwRzLpI3sEMEBCZdkBu6wnvrpoxyYKLvPKbbHXabg4YlV4GeiyL3hEzVrnWrqXBYXqMPV8d5tF1PBzqb9EyvS7iIIjTMBZgFskWQg8vYB4Qk7pv0i3CBSmcJrNHtVaIS8TsPFRj0X/lq8YCSJRJzwxDWXAL1x/KF3h5TxIqy4wdHpSZ/PP8Ptet9AQq1R9J4K8FGZxd13l9jdsrDkK+2R8pS6UaMNnbvwhgm1y1QAtSF4cDRWLo1mixA+iCE4HpguPHUBXC5puEid2ecz/reZ5fZqlMiJspo3eqEcz2GZGNx642Ft9ytuBC60WEhnZ0Lbor7e1jOTYLY5toMXDBwCtpPoqCx7Qk2V6F4jyw7T+m5oODWVuZoBRsYV9dwiLUNVnAgTofer2qkP+YDhe/QCGbq39aNiLbjnbXiF/u7xT84rqRAClc/9j55eYo0pl4GSfBdP7RRkdyZb2WRR1sPwAgaCSFVOwPZ34j/XDQ+1wGfORAkG9mfSLh2nd7xxmd2hKknS1mNtX8bQAy2trVsqsOQawjPmwMPLqQePvFNOReEJttTghU4X0AV2g0FMvPaCQ1Q04Vy/1ED8aL5GzSH7ReUUHXbqI=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-oidc
      namespace: paperless
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-gmail
  namespace: paperless
spec:
  encryptedData:
    client_id: AgAv3Rf+SYRQeq4X3lIsoouZTiz70mM0h/rjB3QLvrQ6YZMG77c4PKq+xO++DvyRwTa9FcjQm3mi6rb5XQ94Hovu72cNCaLp/n/RvQF2t5iuQlDWipWn2TZ7FVuhQHwwIMWH4wAs7Wsk1EdSheOT7YXdZLERRcUFuG7X49Y8cGTu1lhZ+a9t9DJZKjIyBAErloZteLSyMsDSN7zEknKq8uSjWsScriyw5YDoMfwFsOSMXNUAk7CBLC/A0dEoUUkXrwHXV9eZWob4VkooDMBqoA2M4RZ6Q24FZZC8K7sRxZTsP1zvZ3t4dRIxKJD9xlY/zgz+mAjlh5NWW1CirBNlhmx77mRtiNsruRAptX1+bYDz5PewfMtAljHCDIf99t/QXfnE+7MGgyfhyqPhIMDfUO2HZDj/7S23txRhqcI2bv/Gqv3M3phQ/rMsBbNNXMfnEWUgArJRRrNno0aM10co/GGeAieUdbEST3a5Sn2is8mtyI8QBZML6+mc9Y0i36tQc07TM+xfcp13gnVMxAu7tSOCVL6ZjtNC6kEjQpJsgya9xfUvlNh1BkqVwGyrHzeg7jid/atZL9s/kKYKzAcz4ErFKaraCWdc8qD5pXcaiKtTG1f1bgCluf9WrNVKd0UgDZdQ+2S4FuAQwYi1nK+WYjXKTYTdf7/2yXsD1EfnbHU62Gn5xaqCUUZvN+idmBI9WE+/F7ik3h78VOr2QV8Sh6vMcsGMnqPqxFP8/p6GuKHQg9wli2UtAQhjndtvjzS0zC1t8sQGYMETVi7AL8QGBqNbFrVpF4O6pbk=
    client_secret: AgBm4I27zjPyq6DMT7TTeQTcvB7/aF52DDN1lVv5bgS9TgY8up+ElhocNyxmfxfPUe6JhjjIswhqUUl16Ilc9g7wVVpdhnILS7Bt11lSUrZ+CgAYrLfRyKPLKLWG2FrPOd2cpMRMAmnIlB2nrqEmVljmBAGLLrs25C7rL8zn7UvuwojrjVeZUubGRIAWUxeJNUXwXvsda7QLPdvSonaxsmbu0nzBNDNQZ5M9enVg1S9juntS7vUosm1byvVMNvtHb4Btfc1daSSnwN5WJG1GcWKMhqm74ZW5ly8x75zXOrWN6kWa6QT0ZYPtMjIhW+5LPwL/DOtH1T2GcznKkbDiM/RkSK48/L2VRiCd505pgsarIB2YBI4VAVqcpMBfkkbJQiKYzXkQIF0E30k9H+f7UapyhT2mC0bmxoBPGQrB01dGHNQOTc6oXwEQOXBjTkZwXoeHSGfQK1qcUsryFmJYOppDFpCuGsYAsQm2pFiai33M3RFiBEnZlxsrHkKrvxdrsgagPTsAy259RbrW7w7qgor2eoJRqisvbTe/4mDDeHjd8Qmz/sBMM3/l2PNaX2mJ858iHnF9dpK+LSN3eI+ZmQkSTOWxB+8dTOIUcTJFH5xEwKukUzNBKqLqQw3yGEcb+bkpPqluqdrlmooR0nRDX1Fq38SpdJ5WBHyeEPqNDY8Uf+dRdc8yUDK4iKr5NALNEnorxpa/VGTE6ebIWTgwxLNpuuWA2nes06fXnViO5uXSHeLylA==
  template:
    metadata:
      creationTimestamp: null
      name: paperless-gmail
      namespace: paperless
    type: Opaque
