---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-admin-login
  namespace: paperless
spec:
  encryptedData:
    password: AgCxI41lc4TKksuWReEfm7n86v+AH+SbzynKo7HU78uiUTNPnrwwYay1r/zLzdOWNFh2zsjEmx/W2p19snt3VIkyo9LesPJMUHW84VISIIAcfObrFGDg9+XsVuG+SwQs84/AqafdJAprClZU42Tfat5aR8uMFlyVko/lEBYYYYH1QX8Xnk5Zgu1cG1OVsIjCryFEVezsIwh2SyE1BKFb9omAhwR9jev78VswMOPvAzdjUKzZJtyo5pI6FYp1fZsQ0kPf58mE4Hw5AKW/1E5ZXLNrdsBaVPxvFO45IJDFH+vSoQnju7AAlcCHHgexDjlugJEddT6o+rM1L1XqCi+rCNzfQJsHAqRmhfTju/PuaiAZAveyDhFjHXj+fHgqtZIgsjOVkge1oCc6xY0D8Iv9FkrQ/GNEGv+QCDXWg950JpEBiwDApTZuXNG8NNsecHRTy+gIUPY4BsmVCf62thRVVfrRcw5M//DEQkx25Gfq+MThp1vF6Pswxu+GNDZ/6SjLr/0EAePqTkqoQNIs1P5SCcj4FqoUYz1Ewbd01A3Xd6Cw1cZdFVT2YNU5fyi2sF78RReACZ1ic5ldogqrOhQXh8hkrtuyqSb3nnlNmWQXVyW+EOQcLniY+SgpzfymY/oR69AkY5QgAvnSfxrJj2yxbFOV/1EpopAypBpQNM0cKphLQD5ACHPVSKZRgignUOjxFNOC89N40/t6a28IZV87gw==
    username: AgAPDz98oqlEqEu8ee0Nga3p8VraZYl2zqdksOYO+RbGGf+cU2ws0FHBCU6iEi8eSK71lMJg5Mihv0ErEg+O5Y0HaM+fh4JPQccO/t5IWgM04w1SIkFQKJija1aGUAJTCI3Tn9dNEgY4hJMv2QJTy1JXtWUGuJGkUSomxISu485pMJW8ssubocBHgeDQCoSIaQMlUBVn2ERPZseojwpPDbckHknH3KdmF9odP119iAEaCWpbHHVlsTg5Ul6Kn4JkTrq4IrsQDzMU77YSxvVCdpbDTS9RQ12hSRN481fhR2yBeI4o/pDrnQyo7hZbtOgsFmlgGL0rdqQahSFlLulpQgnaCQjR812hH5aupc5Rxj35avrSup0qVe2YGJCBg/m8esFCSlJVzZFgJS2BhAvOeveT+B8rTwlJZm+hsGrh/oudZiDsrgOqNzWjKqxqUbo8CCpYvbAZUmMu8eDNNFBD3h5N+nmdpstA4V81bmMMrk9eBx9WV8odng/I/ojlX2KkTU/U7ypJjyL3bHcqOpk3tcsmca7oRkLDjjdIEe35BeD5AHPj+V6uM+PNCb3j02javNB4tAbQrq3ksvWnYdE7tACkx24l/+XbeUkkorZr6xKYMVTzVmX3HVJt5idEkvuULUd08xSPvdcWyipA8Zezi3mX5G8E2QJeFMrYtBncm7kroXnpRFqN2YYCAhWwISJQYVLonHzVA+AY
  template:
    metadata:
      creationTimestamp: null
      name: paperless-admin-login
      namespace: paperless
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-oidc
  namespace: paperless
spec:
  encryptedData:
    allauth-config: AgCYry4kNs1K0ih4ecEcc8mrG/ioyNYygWV1+yUP4H3tWBrCSZW3nLGwLFDlIzAVCv5r/bgwD9x1hW8vbYY4yQyzN+xvSj5DmVtlzmPhG5Vb43+DFUNay/Wu02p0iRgq6JUtkQVvCOlee70FOtY2fr3wgiQvy5x9Ua3AmSLmC536rsn7FYq1D9RPM/5SyJ+2db57D0rtXQX3sygpjWSZSOM32J8xF2xl+KQgvAIkOw4/Hda941DF9W5JffvF/iaId460hU7hwtrCSjFBplreklH651/yx/x92K2CgTDl3aOQqW4axIRZa5PmwlGh5HK3g7bFyTpyE2u1PS0kD4xK0cJtj/NxKrtJzhe4dBChhnju6oKuald7nfQ1F8fcmsRCuYs0fjsUpx5UEpBYImUbP2PfCiQ2HQXDfLdzctM3In0i8snB5g4zCklgEDS53KJ7nf/CTRpndhX+Abpc5gFE0qx8JWz3lpSlDw9f2lqUNLLwGSEebYgPBEwwoZGngUNmLoFurzqXnTrZOhmkNLQJz8zC1XcyxVXeGpIj4rq8Tj7LR2Ist5konjleK48x/RnKHZE0BVbhnkAIvavljXI1NnSyM5JlQISZHiXWDgXKwzlfjg2rUPMYoWUD3llzkZTyaxM3/CDLzX/0PgN4VjxcQHGoUOfrPvd6On33s8smRW0Qcfh94Zvl7V6ayAo9Cj8ePSWnkI2IdcliWGRO9TmPoQTAyQZmXIhvXVA1QPfKXD1bA24+bJeKYriMFSoPweaTUgv4p+uBxdlvp7w1oC0k0RHkPs2IUzL7iaUpFwh6LidkY6+5Ww1UhW/9HJ/Y8x99cNqSlpIITqysaAau5gx9Gq1NKpCdnMwsIKP0LyrAHCS752gZclN46yAofB+GpvVoN7xGpl4lzFsLz5wGfp+FZ4FhT6hxVKwi91yTzk3ez+LeCUFtCYCtf30uUJZfFq6c56RCHe/SQ3APYPZY1yj/BEX86T615mshZCfh0UwTvOEuPO5lK4Q+DJd8Yk9gXFP6ZWSg2ahR8a5zCLStDcpszJjSXRhuBxXwx+SLdle9Kyj/dlmjkCurUsBD80+6m/KT7SWXcGBXny8wM6BdajWMrKaxt0uM7p2mCKbtLas5XDFeAuXz3rgH/vpQfXIbmbVp6Zzci4JpSdswQgu3xU8IC5NLUTyPL+hMqOzSCxDIJSelUg3ntuEaUERdWGsUXy6RQuE62d+tCxvWhF8=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-oidc
      namespace: paperless
    type: Opaque
