---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBqqVxy5Zcc/R5BI0iH+fXgY3GMrywHsCkxqoXFXwdD0a9Lj8KLlSw7RNbhkLQIeoREm5CxN8P9/Mu/cmZt2h6ZL6XQeNDRqEk3c5FyUE5V5lRYt7KFl9tlq/FFZmdODC4ho+w6vg2PSiR4oPP4aWhif3TL15hnCyhw/kpoFC8rji1+qZqTmWn88nvUn1gVbI4EUqTnxwa/xAQUJk2oH5xqlkqebBPwVKPP9Vx/DJwTZAYaHuyC1s/NGaoYsqxGVeY7HlRs4iPbsaUsaADShSp1Dbl5n756h7GQKF6aBgkvvVQrvNh6G/wvDRUuQ+owEhNK2soQHmFUnLKuK8RBBAHnaRwgsbd3Y52lbloMzTzM7+/fT/QdBjHFyY3uY6s+e4OZrSDWKEINgt+fSzUOJozoDViPW6RhMSrIQbGi3iYO+GSYVIXbAhib4R7+zKkJL1gDneNscoJtWZvlGkVd3tD/q/clzipnoPAa2CMcIqunC+Yj82zUyhDf4uEX3fejvDgDnWYjalbqc2b31qZQUm6FGzxEp7Q2MWTJYu3ZlQx5DZcUY2i8ZhyspH5DJbuFKWG8UF00xo7lUDVTTEfXWd5+op9AyMnwzl8g6jVVsvP43sJUM2709B9jHvxkIJP+fNRQPlkK1e53t6nfbb1xw4qTzLD3ZK/j5fZjSGo82G9EgHh9boCqBXfoGM2BqvAGiGiTie23q2VCb8bZhznTaBk53S8mVQ==
    AWS_SECRET_ACCESS_KEY: AgCKdMg0iEe5fa+dfNBSNYWJXGcqd9TgQmsad8q6AQFUzDA0+b7gynk8LTZUhh6VjfiQrXAEPCKWV5O0usw5rARlQfsCZoVyp/mztsKQ/oTCdS7qiUVhGGiVkN+Fi2jqC/L2VY19RX/j1egpb1q5u8cX3Iohe6NaDW7JWvE9VgKv4JnZzDnLPhvuFJ/BxWn4+fhacIH5NhH7EOKQpRBGpVVmIuUvrCs6+rZC2xzWbpIbRmgdx/fXn21e0/EeiGfM2zL1cXbHTlPIpY0gENHsioj3HxHIJvFrXF9Y8m9Sg0KNlrMLjbw3JMoKs2JAXry/ixWxSTRMSjAvMJIJvn0ajDg7gsczOH7p8mw6bOjh+ZVvk7zSCQsBmV2TUwYgV4WxUXlLKNT50TnucjW3Luh4oINeOojSbq9Qsm9VSUKzmXxB5hPMor/GHxV3Pq60i4hZjSP8n/ZsFOMEk8fUFsAOotRM/bS1GvrSzd0dsTCCBVNjVDeInnXNsaC7K7ElcijWmJh2PNecYvGcQg9MQr6Jv5rQ62ta72YXkabGdH0SueL/woXwuOrS/Zb4vuEE1u43LuUDkbQRRhZlx7VK/am8QTdcbo1iB/VBB28D+sYXrXZciFtXc1K0z8GhulVWKBXAv9c+SBL0KwhW4Ag0FtGEl70e4mCfiC++zhCy4mRExUJDknvz8XWJAEzTLouAPazrIYQPWxsx3FBO1of4PmpCAvwAFjfntJWfjwAfBjhLjE/+A0hzOvu5xNST
  template:
    metadata:
      name: s3-credentials
      namespace: longhorn-system
    type: Opaque
