apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: ldap
spec:
  selector:
    app: ldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 636
      protocol: TCP
  type: ClusterIP
