apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero-release
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      version: 11.0.0
  interval: 1m0s
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.10.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      features: EnableCSI

      backupStorageLocation:
        - name: default
          provider: aws
          bucket: lffl-me
          config:
            region: eu-central
            s3ForcePathStyle: "true"
            s3Url: https://nbg1.your-objectstorage.com
          credential:
            name: cloud-credentials
            key: cloud

      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: eu-central
          credential:
            name: cloud-credentials
            key: cloud

    metrics:
      enabled: false
      scrapeInterval: 30s

    deployNodeAgent: true

    schedules:
      daily:
        disabled: false
        schedule: "0 2 * * *"
        useOwnerReferencesInBackup: false
        template:
          snapshotVolumes: true
          volumeSnapshotLocations:
            - provider: csi
          ttl: "720h"
          includedNamespaces:
            - "*"
          excludedNamespaces:
            - "velero"
            - "kube-system"
            - "kube-public"
            - "kube-node-lease"
