---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBAhwfNkHNO3PuAoI1M4uModXU5i8ABl5lf4WzZesuS9C6VjmoKeMc8CdvUoQ9gZL1tMFlQm+rec5UA7/zk/76ySs+CrcnYlqm70TobMKyDEjT+yx0qJX07gUnDOv21ADzifiHp1yvKPSZKfZ67wXRYBtJqwW0CgAwvo35fTtI973NcXQfX6atbzpCrKukbLqHTcfDzWisiY1Sp1FxkkgSTMWlrXz5GwAuQSLwg7Nvsly4dNXAuXOkDUHGA8mU6zGs1i6g42udu+Z/cUtHPMjQswizTjQC4uk1sR8IgQu1o9JJ6Sh+zhy12qwfquXdpTwOxChWarj3SKQcx7YwPE55nYGGI/BbfjkWX5o17ZMMZDIIGRetZWF58pX+q0OBmwAUCd9uUjKQSqRygmrsexdE09bx2oksZrgt+5rU62KXzKAHzUk3elUnP91rBjE191xmcpCicHxHwddL2kQ06pl/eY3Y44AyD6Yuwq8VCPHOMdgzKJJ1uv43ms1+g2XaQ0alqaldUNpXQD0lKhIKJ0Fc5B+t6sMovWFkT2OLbkYxpbmQOkpjDsg9EPM1RSOvouvdPsokgvGFZLhhU5Rx3U8oGj1+Bf9+s0ek0TVPLV+08SdFHUsvggI4/NGebwd35gOc9he7v4+rw2DH+T0b78E80O47E6G/CwKAcxQ7W+ELjB2jYivELrLwdq3loaj3MDGw91Px6Qx48Di1ReI5Eo/lF58j0q2GhmARsIbd01N/nw9j0k3AsTLseu5E+HgprksA46YX+hWOVGmfdjKpqrlBpEP0HdVhqygZIhhSzEBr5F0OxdzM/BgmN5WiAAkcwn6DEsu5IXWmNg9tw2jTXbn+8
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque
