---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAQptPU7CZjV4mBBT2SUKEkgrJPDS9hAqgwcaEFIPiBmvluVHWjx6il9OXvMfgHi/iraGTda3YTwdRH0a4bbnHG/sfUS7DHdNTed387uOkLFiUccfA+5JPT/Jp2np379vxhMbJ1+gUUPpM57Z0BfXYW8hOssr3Q6s3qFcKANe4iI9S83MhiRZSn4CqDH0TiVLPM29om+mHAt2dy/Gxk0qRlvJdtAkmCQzdh3h4j8OYqm1KCCZW8QQVUsEBjtjqqzw89/v2Q/1rl5u0UdfESC1QjVAfPNr4j7Mpo7bZfuBgZ6Qbd+jHDFP7wgnJtySSC5NTHeu58MV0A18MqX24XA/6O3Ujkr67qv5nEJeqvXSx6I5WKZmMF0K/268G0Nz52TdiuCx1pY5LnOsR7BJDsyuCIt2m2iswv7oeiLh2rEmP1BKZ34RoA5FiFotTgDeUx5KXegIWtV01PBo5KdgMsMvyQHVsSOp43l63v3ZkPrgbKY91iJlpuWGFmhIc9l0k8BTfV/FUK4xF3+ziRgrtXBJC84NORjyG+79dnezn5/D5AETZsAGimrmzrkIauXn/hCcVS0ATUH6ducMbaC4unfRoCzYvsmwHgkyTHGu1w04ntguXUkD4GoVU/dfgVn5n/fYzPf/Z8V7nUUvaC4a1ce04EjIpmy9emPrwIBJ70MBZ3WhzhTpjD8ncyi86m6ZfmYvvNrw8v1VNajOkDaU5J+LhMyiMK+fNkBywX+J/Awka6JMwRN7ykbIy8jiIrRAFjRDJVywcLyo0+vGFGDFZCkblyOC/jeO5HzOBTsyvHXU5Ztn5xht8EZDO1G7Oo6HIexfuNRHPnm4dEo3v7xeJpDNKz
  template:
    metadata:
      name: cloud-credentials
      namespace: velero
    type: Opaque
