version: "3.8"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config:/vault/config
      - ../../data/vault/file:/vault/file
      - ../../data/vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    command: server
    restart: unless-stopped
