apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheater
  namespace: cheater
spec:
  selector:
    matchLabels:
      app: cheater
  template:
    metadata:
      labels:
        name: cheater
    spec:
      containers:
        - image: cr.lffl.me/cheater
          imagePullSecrets:
            - name: lfflme-creds
          name: cheater
          resources: {}
          env:
            - name: OPENAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: cheater
                  key: openapi
          ports:
            - containerPort:
              name: my-name
      restartPolicy: Always
      imagePullPolicy: Always
