apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheater
  namespace: cheater
spec:
  selector:
    matchLabels:
      app: cheater
  template:
    metadata:
      labels:
        app: cheater
    spec:
      imagePullSecrets:
        - name: lfflme-creds
      containers:
        - image: cr.lffl.me/cheating:latest

          name: cheater
          resources: {}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cheater
                  key: openapi
          ports:
            - containerPort: 3000

              name: cheater
      restartPolicy: Always
      imagePullPolicy: Always
