apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: couchdb
  namespace: couchdb
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: couchdb-auth@kubernetescrd
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    traefik.ingress.kubernetes.io/router.rule: "PathPrefix(`/`)"
spec:
  rules:
    - host: couchdb.lffl.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: couchdb
                port:
                  number: 5984
