services:
  wireguard-homecloud:
    image: linuxserver/wireguard
    container_name: wireguard-homecloud
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    healthcheck:
      test: ["CMD", "ping", "-c1", "10.13.13.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SERVERURL=loeffelmeister.de
      - SERVERPORT=51820
      - SERVER_ALLOWEDIPS_PEER_homecloud=10.13.13.0/24
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=15s
      - LOG_CONFS=true
    ports:
      - 51820:51820/udp
    restart: unless-stopped
