services:
  wireguard-homecloud:
    image: linuxserver/wireguard
    container_name: wireguard-homecloud
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SERVERURL=loeffelmeister.de
      - SERVERPORT=51820
      - SERVER_ALLOWEDIPS_PEER_homecloud=10.13.13.0/24
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
        # - PERSISTENTKEEPALIVE_PEERS= `#optional`
      - LOG_CONFS=true
    ports:
      - 51820:51820/udp
    restart: unless-stopped
