services:
  wireguard-homecloud:
    image: linuxserver/wireguard
    container_name: wireguard-homecloud
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    healthcheck:
      test: ["CMD", "ping", "-c1", "10.13.13.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      # reverse proxy config for traefik
      - "traefik.enable=true"
      # Router 1: internal.loeffelmeister.de (higher priority)
      - "traefik.http.routers.internal.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.internal.loeffelmeister.de`) || Host(`internal.loeffelmeister.de`)"
      - "traefik.http.routers.internal.entrypoints=web,websecure"
      - "traefik.http.routers.internal.tls=true"
      - "traefik.http.routers.internal.tls.certresolver=myresolver"
      - "traefik.http.routers.internal.tls.domains[0].main=internal.loeffelmeister.de"
      - "traefik.http.routers.internal.tls.domains[0].sans=*.internal.loeffelmeister.de"
      - "traefik.http.routers.internal.priority=100"
      - "traefik.http.services.internal.loadbalancer.servers.url=http://10.13.13.2"
      # Router 2: other loeffelmeister.de and lffl.me (lower priority)
      - "traefik.http.routers.otherloeffelmeister.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.loeffelmeister.de`) || Host(`loeffelmeister.de`) || HostRegexp(`{subdomain:[a-z0-9-]+}.lffl.me`) || Host(`lffl.me`)"
      - "traefik.http.routers.otherloeffelmeister.entrypoints=web,websecure"
      - "traefik.http.routers.otherloeffelmeister.tls=true"
      - "traefik.http.routers.otherloeffelmeister.tls.certresolver=myresolver"
      - "traefik.http.routers.otherloeffelmeister.tls.domains[0].main=loeffelmeister.de"
      - "traefik.http.routers.otherloeffelmeister.tls.domains[0].sans=*.loeffelmeister.de"
      - "traefik.http.routers.otherloeffelmeister.tls.domains[1].main=lffl.me"
      - "traefik.http.routers.otherloeffelmeister.tls.domains[1].sans=*.lffl.me"
      - "traefik.http.routers.otherloeffelmeister.priority=10"
      - "traefik.http.services.otherloeffelmeister.loadbalancer.servers.url=http://10.13.13.2" # Replace with your actual backend for this router

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SERVERURL=loeffelmeister.de
      - SERVERPORT=51820
      - SERVER_ALLOWEDIPS_PEER_homecloud=10.13.13.0/24
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=15s
      - LOG_CONFS=true
    ports:
      - 51820:51820/udp
    restart: unless-stopped
