apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.lffl.internal`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
  tls:
    secretName: self-signed-cert
