---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gameyfin-secret
  namespace: media
spec:
  encryptedData:
    app-key: AgB3apu4cw6sOTMpTNaRHZ0KucvvMON7KsczD1RzjmyOrOLknRzUjjYOXVadvAOyDg5mmcYSbzCjPAliHGPCX3Mhroh2/Ox+yBgKjrpyiXaCpNolwGnJWBVTE3I2Cz7kbvrJGEJZd7WKxmGsGs9dtzc1jdMoW3qZYCsTRKyTAYYFmsROB1/RMbjqHSIqkb6JO/PZoWFTOuEid6FGBX+1pw0GFOrQUUuvJXqmRNAkw9sxFpMtEevEvSJ4UFrXhxWFuvEOXCwsDTjAPKJ+aVckLJ5eksDUoYRTPWJroCaehlDE8XVPz3pk4wpPnp9BtqzgbpOPD2GURssxJRZq6q6qsYHL0ud5+t/Q/BIh1NkBZra3sCBwfZUutJnqDPAMs2aLID0kQSxtZKeWGgnVOLdFgZ9BXtEqPRTqkfghdDxy1e5ouTfzNm0DuRQX9+9XuSLVTpgzdgdBRSvQ/Ep2rj3oTlBTTbZeIIsCw71lFrF8EV3qnP5A+1+jeA1tgu0cmuIi/kPTDkbqODkK9wh1zLd1OI+ENv3aMUq2Nth4/sosLKbHTBG6f+oXdCagYrYa4v9bH9bZyJdAMaBPg4H55EWxeIEA/tUuFXjxpLuKp9aBow4vQXyCfzzbXe+lkppZcTXySHFpYFs9CtiSJYQJGJ1ZThfHl8esFzENSrXFJtIb5UaF4gw7NzS5P1lk3qVoa0NNR6uKalw3XkODo95hwnUb7gzsG5SWhrT+6wyesudRscxvxJjw2PMplt8a9anCRQ==
  template:
    metadata:
      name: gameyfin-secret
      namespace: media
    type: Opaque
