apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      formatter: text
      fields:
        service: registry
        environment: staging
      hooks:
        - type: mail
          disabled: true
          levels:
            - panic
          options:
            smtp:
              addr: smtp.eu.mailgun.org:2525
              username: noreply@mail.loeffelmeister.de
              # TODO: override with env var
              password: password
              insecure: true
            from: noreply@mail.loeffelmeister.de
            to:
              - kraetschmerni@gmail.com
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
      tag:
        concurrencylimit: 8
      delete:
        enabled: false
      redirect:
        disable: false
      cache:
        blobdescriptor: redis
        blobdescriptorsize: 10000
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
        readonly:
          enabled: false
    auth:
      token:
          realm: https://auth.loeffelmeister.de/realms/loeffel/protocol/docker-v2/auth
          service: docker-registry
          issuer: https://auth.loeffelmeister.de/realms/loeffel
          rootcertbundle: /etc/distribution/certbundle.pem
          jwks: /etc/distribution/jwks.json
    http:
      addr: 0.0.0.0:5000
      prefix: /
      host: https://registry.internal.loeffelmeister.de
      relativeurls: false
      draintimeout: 60s
      http2:
        disabled: false
      h2c:
        enabled: false
    redis:
      addrs: [redis:6379]
      db: 0
      dialtimeout: 10ms
      readtimeout: 10ms
      writetimeout: 10ms
      maxidleconns: 16
      poolsize: 64
      password: password
      connmaxidletime: 300s
      tls:
        enabled: false
  jwks.json: |
    {
      "keys": [
        {
          "kid": "LUfhcK1AeLUGfx1QUDNGQ_JV3cqM0jmHjbERaSkbVOE",
          "kty": "RSA",
          "alg": "RSA-OAEP",
          "use": "enc",
          "n": "kVACjcqhSw6ZU4MJYlOE4VeLqZIchEvC7IvSa3mSGsoHoXrnpiiLzWwQlcUBD2Mp848tYI23t_QVcASBdeOh__p4QG-vk59r32oyYwN77l42sFIOIFlfAS6_-0EJaVqis-G0dGYmNoIEG7YgfkvhiH3fCl3EgZ5PYvj5Uu8hy2IUodOHnRqfU0iRYoH9zKzj1ojL_8lK7nqdOrexyRJV5PJ2ntiefMEcoYXBgDMU89r9T8UuuRFzvLvkWwjrIgb6bH8nMwzo2HEbsSyUbCpMy8GBcm-JcT0DiEB_EYZEFaCVxXMurmatROyTD38_4X_fPPTMCidBKaE6k5YTPhKJiw",
          "e": "AQAB",
          "x5c": [
            "MIICnTCCAYUCBgGMhDSvWTANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdsb2VmZmVsMB4XDTIzMTIxOTIyMjk1NFoXDTMzMTIxOTIyMzEzNFowEjEQMA4GA1UEAwwHbG9lZmZlbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJFQAo3KoUsOmVODCWJThOFXi6mSHIRLwuyL0mt5khrKB6F656Yoi81sEJXFAQ9jKfOPLWCNt7f0FXAEgXXjof/6eEBvr5Ofa99qMmMDe+5eNrBSDiBZXwEuv/tBCWlaorPhtHRmJjaCBBu2IH5L4Yh93wpdxIGeT2L4+VLvIctiFKHTh50an1NIkWKB/cys49aIy//JSu56nTq3sckSVeTydp7YnnzBHKGFwYAzFPPa/U/FLrkRc7y75FsI6yIG+mx/JzMM6NhxG7EslGwqTMvBgXJviXE9A4hAfxGGRBWglcVzLq5mrUTskw9/P+F/3zz0zAonQSmhOpOWEz4SiYsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAW7GVuJPs7THj6pK0V/FXX66qJi0k7apGHzYn+T2gc8e8+jG2TOgAfl7wA+3Wy6+5XKxpNCe2UqVUyY2VfqTovfiVqe55zDk7qv3fSN9JSJK0BRrlf4HTDRrlzLJnh0eESmRxYiNSa6Ebz1Om0LmG3i4va9d0eRL4Oj43Z7Gjs9lRlYCWFU7rYSkX+XDS0ic8BTYEJRdHUfBIs7OEURFtbjD8DGfhCmCAz+CxDBre1ipc+kB0KMV51ubYwq8SVeu+e3m9noxplg0qbqhv9SA5hg54wDetf1fsLDVLmhnzTv4Co6qL3CDlCBsfCBMFIUhUt9xDNkMMxcNDN9yGxfjKPQ=="
          ],
          "x5t": "JyiuuOgv6hTXgZRTPaa_Jk_Yuis",
          "x5t#S256": "kmWlCWQDMcw0FKjhwT1ODlweRceCSTEIqlE6CK5BrNc"
        },
        {
          "kid": "HOZONRLbMfdFupwgOqXkcQu0vV98iHQXQNunQtOndGk",
          "kty": "RSA",
          "alg": "RS256",
          "use": "sig",
          "n": "j77gi9xVKwS6HSc26KrelYtBRJRQclySmoB4k6sd1joNvGDvrOXWbdWV2ODb9r-A-sHdA3LY-GsgSl_N-WjHTd0eJMmKtIC3rbhUmQuiTXrLE8Gg00cMBra0Ir9S1n6sGvvjm8d-cqT_QcnJ_ZTg4v8q2nc21w6CfMRExi69o2YlIV3K3H7JMebyEmpTm8i6LMnMKZsLZGMe8JRpBbWB6GiqNwWgIxEcfaSp1XTNhLbI1lD7OIj6QKSM28I7qXqoPaP7FFMvnt_aIQSZR8VTXdw-UTNIspQsdldF-AXNdD3-jj07at7bILbypJMHJvmegYTGekNiGS29tZr486IUDw",
          "e": "AQAB",
          "x5c": [
            "MIICnTCCAYUCBgGMhDSuQzANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdsb2VmZmVsMB4XDTIzMTIxOTIyMjk1NFoXDTMzMTIxOTIyMzEzNFowEjEQMA4GA1UEAwwHbG9lZmZlbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAI++4IvcVSsEuh0nNuiq3pWLQUSUUHJckpqAeJOrHdY6Dbxg76zl1m3Vldjg2/a/gPrB3QNy2PhrIEpfzflox03dHiTJirSAt624VJkLok16yxPBoNNHDAa2tCK/UtZ+rBr745vHfnKk/0HJyf2U4OL/Ktp3NtcOgnzERMYuvaNmJSFdytx+yTHm8hJqU5vIuizJzCmbC2RjHvCUaQW1gehoqjcFoCMRHH2kqdV0zYS2yNZQ+ziI+kCkjNvCO6l6qD2j+xRTL57f2iEEmUfFU13cPlEzSLKULHZXRfgFzXQ9/o49O2re2yC28qSTByb5noGExnpDYhktvbWa+POiFA8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAZnxaqJcylrJfjo7Oma6YApvPSTyEEkCJlQIBOYeuVgbtwfMkDgDJHFNAqIDALhJtd1PlGUM2qhSbGT4ycLfkOoyZFHqMaiyPPAPdsct0cd2Z1YNTA6JT43a0z8Lg2LaV1ym9rpmDJQnbTyM3PW9l27Lbl+KpPHbYCeiXWX0mAgF8EYVid4BDVtnnT5qevhCkc/eYdEpCIkRn5i9mmKo5Nps5ed/rEpXEBrz+gIx7L5BhJXlGRJq+fe9KQMO7F/n9lTTiyOgVjyw0wUW9QHiHnjuHpQHcvQF3Cy3p6TecLFlFAuBCbyqjVBuoSnGGw91Fj7/rEq/z666qnCKHufLtQw=="
          ],
          "x5t": "LQV10LQWND65jGNzgE2AzL21bXQ",
          "x5t#S256": "tafv3iROVnDVzTSTHXC49GsAufsPh0VNFVQ2JxeztQY"
        }
      ]
    }
