apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      formatter: text
      fields:
        service: registry
        environment: staging
      hooks:
        - type: mail
          disabled: true
          levels:
            - panic
          options:
            smtp:
              addr: smtp.eu.mailgun.org:2525
              username: noreply@mail.loeffelmeister.de
              # TODO: override with env var
              password: password
              insecure: true
            from: noreply@mail.loeffelmeister.de
            to:
              - kraetschmerni@gmail.com
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
      tag:
        concurrencylimit: 8
      delete:
        enabled: false
      redirect:
        disable: false
      cache:
        blobdescriptor: redis
        blobdescriptorsize: 10000
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
        readonly:
          enabled: false
    auth:
      token:
          realm: https://auth.loeffelmeister.de/realms/loeffel/protocol/docker-v2/auth
          service: docker-registry
          issuer: https://auth.loeffelmeister.de/realms/loeffel
          # rootcertbundle: /etc/distribution/certbundle.pem
    http:
      addr: 0.0.0.0:5000
      prefix: /
      host: https://registry.internal.loeffelmeister.de
      relativeurls: false
      draintimeout: 60s
      http2:
        disabled: false
      h2c:
        enabled: false
    redis:
      addrs: [redis:6379]
      db: 0
      dialtimeout: 10ms
      readtimeout: 10ms
      writetimeout: 10ms
      maxidleconns: 16
      poolsize: 64
      password: password
      connmaxidletime: 300s
      tls:
        enabled: false
