apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: registry
  name: registry-ui-proxy
  labels:
    app: registry-ui-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui-proxy
  template:
    metadata:
      labels:
        app: registry-ui-proxy
    spec:
      shareProcessNamespace: true
      containers:
        - image: nginx:1.28.0-alpine
          name: registry-ui-proxy
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources: {}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
        # Config watcher sidecar container
        - name: config-watcher
          image: nginx:1.28.0-alpine
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache inotify-tools
              echo "Config watcher started..."
              while true; do
                inotifywait -e modify,create,delete,move -r /etc/nginx/conf.d/
                echo "Config change detected, reloading NGINX..."
                nginx -s reload
                echo "NGINX configuration reloaded"
              done
          resources: {}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: registry-ui-proxy-config
