# /var/lib/registry
# REDIS_ADDRS_0=service
# HTTP_SECRET=secret
# LOG_HOOKS_0_OPTIONS_SMTP_PASSWORD=
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: registry
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: registry:3
          name: registry
          # livenessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 90
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          env:
            - name: REDIS_ADDRS_0
              value: redis:6379
            - name: HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  key: httpSecret
                  name: registry-secret
            - name: LOG_HOOKS_0_OPTIONS_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: smtpPassword
                  name: registry-secret
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-config
              mountPath: /etc/distribution/config.yml
              subPath: config.yml
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-data
        - name: registry-config
          configMap:
            name: registry-config
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
