apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: registry
  name: registry-ui-proxy
  labels:
    app: registry-ui-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui-proxy
  template:
    metadata:
      labels:
        app: registry-ui-proxy
    spec:
      shareProcessNamespace: true
      containers:
        - image: nginx:1.28.0-alpine
          name: registry-ui-proxy
          # Add this to ensure NGINX creates a PID file in a standardized location
          args:
            - nginx
            - -g
            - "daemon off; pid /tmp/nginx.pid;"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources: {}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
            - name: shared-tmp
              mountPath: /tmp

        # Config watcher sidecar container
        - name: config-watcher
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache inotify-tools
              echo "Config watcher started..."
              while true; do
                inotifywait -e modify,create,delete,move -r /etc/nginx/conf.d/
                echo "Config change detected, reloading NGINX..."
                # Find and signal nginx directly
                NGINX_MASTER_PID=$(ps -o pid,cmd ax | grep "nginx: master" | grep -v grep | awk '{print $1}')
                if [ -n "$NGINX_MASTER_PID" ]; then
                  echo "Sending SIGHUP to NGINX master process $NGINX_MASTER_PID"
                  kill -HUP $NGINX_MASTER_PID
                  echo "NGINX configuration reload signal sent successfully"
                else
                  echo "NGINX master process not found"
                fi
              done
          resources: {}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: shared-tmp
              mountPath: /tmp
      volumes:
        - name: nginx-conf
          configMap:
            name: registry-ui-proxy-config
        - name: shared-tmp
          emptyDir: {}
