apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
  namespace: flux-system # Adjust namespace as needed
spec:
  interval: 1h
  url: https://charts.jenkins.io
