apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdroid-data
  namespace: fdroid
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
