---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lfflme-creds
  namespace: photo-upload
spec:
  encryptedData:
    .dockerconfigjson: AgB4Awda4IxMZM78aPsCyA09935CZXnr1O7+V+/wzkj2eofOhXCpw2rerp/t2lMER/7S2DzMiq1Pso1TieqFfMjVY1gc48XxDzh7QYtXh+zM2z2nMk0vbrHOX0u3QLXsFR4gpFQTZqDJWh+tET7YQwMR6Iwexxy5nNEMWztZg4DbZGqkykpTJxA6BaKJkhiSWdsA1qSgJrb1Fs0ehZkUDvT3Aul9ihOwr2foZgMhqMGrQFbS1fo4hEk06x0rylTpZaCaSN/BLE2HlBG2T7F2oOUYonGLNswptTjtH1YFgU6y/Q4CiC3nwWNp0tMGnZnUsXZ+IWFZCQf0Slta7EaqmaI8kaVJsKikoJQKx8Pg4EabMoT4STzO86kHdfTK+S9JkwfKhvwRPAUnG2kmDmxQeYZy4oeC/+83HvtQNp7QGcLnennqybb8faZPoehrvaJBGvhGDCev/dZoLE/S7SxbVAn8EUGZhHzbyZiZZ/H4HRLJe7HGrZKC//Fd6tAahGydsBk/VmufTa+cyCOwIW8FQvcYZYDGk5oBgjgM9gxL+eN8gevRTSI/6UzJZ2/jC9Yxa1SHvKrjGCv1sZUYasllQshEfibQQFwAcdklKS8DGBGao2Z2bVD91ZtdPKxDgXayzpIJA2X7jg8LG/dJWf/64RRoCXBzqfim8YYkKtwvGCuF5FybMZAljmxQQ9CR/PpG6edfjf56iEgKhcckkOHqNk5cBqV0gxfPXVH9skyYTjNhVjLaYPoPrOo4VSARAqPy5s12rxz0r+XqDGCjD7H5ode9VVJx+DgLivoXeIVwxRHP6uwhRL+8/yq1FLhAvQdB8+JkLUs4QjM9zQ==
  template:
    metadata:
      creationTimestamp: null
      name: lfflme-creds
      namespace: photo-upload
    type: kubernetes.io/dockerconfigjson
