apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wireguard-homecloud
  namespace: homecloud
spec:
  serviceName: wireguard-homecloud
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-homecloud
  template:
    metadata:
      labels:
        app: wireguard-homecloud
    spec:
      # nodeSelector:
      #   role: ingress
      hostNetwork: false
      initContainers:
        - name: copy-config
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /config/wg_confs
              cp /secret/config /config/wg_confs/vps_tunnel.conf
              chmod 600 /config/wg_confs/vps_tunnel.conf
          volumeMounts:
            - name: config
              mountPath: /config
            - name: wireguard-config
              mountPath: /secret
      containers:
        - name: wireguard
          image: linuxserver/wireguard
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: INTERNAL_SUBNET
              value: "10.13.13.0/24"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ping -c 1 10.13.13.1" # ping VPN peer
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ping -c 1 10.13.13.1 && wg show wg0 | grep -q 'latest handshake'"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: wireguard-config
          secret:
            secretName: wireguard-config
            defaultMode: 0600
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: modules
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /lib/modules
    type: Directory
  accessModes:
    - ReadOnlyMany
