apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wireguard-homecloud
  namespace: vpn
spec:
  serviceName: wireguard-homecloud
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-homecloud
  template:
    metadata:
      labels:
        app: wireguard-homecloud
    spec:
      # nodeSelector:
      #   role: ingress
      hostNetwork: false
      initContainers:
        - name: copy-config
          image: busybox:1.37.0
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /config/wg_confs
              cp /secret/config /config/wg_confs/vps_tunnel.conf
              chmod 600 /config/wg_confs/vps_tunnel.conf
          volumeMounts:
            - name: config
              mountPath: /config
            - name: wireguard-config
              mountPath: /secret
        - name: cleanup-interface
          image: linuxserver/wireguard:1.0.20210914
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          command:
            - /bin/sh
            - -c
            - |
              ip link show vps_tunnel && ip link del vps_tunnel || echo "Interface doesn't exist"
              exit 0
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: "1"
      containers:
        - name: wireguard
          image: linuxserver/wireguard:1.0.20210914
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: INTERNAL_SUBNET
              value: "10.13.13.0/24"
            - name: KEEPDNS
              value: "true"
            - name: ALLOWED_IPS
              value: "10.13.13.0/24, 192.168.0.0/16, 10.42.0.0/16, 10.43.0.0/16"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ping -c 1 10.13.13.1"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ping -c 1 10.13.13.1 && wg show vps_tunnel | grep -q 'latest handshake'"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
            - name: modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: wireguard-config
          secret:
            secretName: wireguard-config
            defaultMode: 0600
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: modules
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /lib/modules
    type: Directory
  accessModes:
    - ReadOnlyMany
