apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: privileged
handler: runc
scheduling:
  nodeSelector:
    kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wireguard-homecloud
  namespace: homecloud
spec:
  serviceName: wireguard-homecloud
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-homecloud
  template:
    metadata:
      labels:
        app: wireguard-homecloud
    spec:
      runtimeClassName: privileged
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: wireguard
          image: linuxserver/wireguard
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: wireguard-config
              mountPath: /config/wg_confs/vps_tunnel.conf
              subPath: config
            - name: modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: wireguard-config
          secret:
            secretName: wireguard-config
            defaultMode: 0600
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: modules
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /lib/modules
    type: Directory
  accessModes:
    - ReadOnlyMany
