---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgBEQjYKC/80WcJF7rMiNqz9LOo0h9n5RQfkwmPdXsY5I16FyJCo7kujsQRWD8mWwLzn7cxVY1uqTyj4dmX3CA+acOuSJ0krmE5u1+g9Kv8hDqVaaboYBtsV02hhbGJHHsOYn9WxyKG+ksx/zh9BpcU1gw2W/E6I3xXi5aqz3iHheubKSqp/SYuD+LqvtpsjIQ1ej8OkA5XCejenuYqAcB2va4lL0u4+fNi/r4Gh3KX4F3yl4Ytt9nABHQyc/buXiZNnDol/9K2LCx91JU7zPkHkCYske5Cz4djJb5vZ8gaN8rm/sZWOyPmJp7LwY7xfiIilZ/8Es/QXPEWR3kU84zvXZaxNwib+vVJQj0PhsWZVoM4ERwYndd/5kkn+Ua+9h55XY2R8gg9q9GPww6Y1CjjattLje0seDNqNW2n2Xr1qp//qm/T/Zt8DEpSJD5gGbzb/0R0jKmHmHnfrH7xb8zFKowtZC2IFHNl1wCv55lk+1tcKx2L3NQywKgTT1Ulqz3oYeXmmjHqhX/Ffg6IDefJky8IJdIvZQKATfEFm6Oe+DlIl+ok3OjwleUyAQHTy1fG58tQtz5VMfJN34IwI5FzGx4Ttvu5FcpMsMt/6FzpcPHhoy9caVw7GB97Q5TOiwN8X5Hxeb97/WpGTTVR+IqChRP6KfIlUrKb/W5njCGq4I8Enthg2L8ZtBTy7grNWXhbJ2JZZMuMa6e5uWzEdogvqPu1ssPc0rK/sirBaaeAZQovL8xiEPsdVut7KGXpumbKW+/nW2sr3iTTPKqwPSYgRJQe0LqN8qXoPQUFUCIbn0bGUOSd1R5Q8ICRA8ad2MJVlFEU9ZgWv/V4qli9LqEkez3cfkszIJB3u6X6pkt7wx3Njhg/0pOof8HsnMJ30tSel0Mh3whFU0opK0L9nNZ/urHXKXCi5K7FcdrvClinO031F733BPuHsUJJ4HK8KeCx9rfPC8qaEdas2ud5HeYE4qCv/qqwFQ9jMiixOJm3NsstN0jmswSAZY59rBBqBfoM9tY3gnhou817ou+6crQ7dcBEXuPh5J1kJDKLsKGCF6Wvdxom0o1u9kBmBjrcXUTq+aNjo0cjXxLVHh5NXn3+JUppRriSGFPVF/dlx+AA+v7JZOv2SBBqb3txvJfUUTLq2SX5atwEj8LnUNm3RDTVsv9vPwySNASN5iZmoukCqTLh0js5WmREcmM6u6oBbJyb86etmg9dmlczIjWainY/SgXU56KU1itVEXSzE8XLoJcrtzF+JYKYvkMuVN6WBK0aWCFYhHDzsYcYyRqs0GlZfSKZzrWPXxX/s8mQLyncnMFXRvRadt4ZDDWITW0Z43rJ9j+Swy2pYjIUc8hKeeb3AChZNfl8IXZgzrWxXWv855EQ7nt97AKIV6DcxMaBGmxG3Vx4p2ExwN5+VmqIuZzJVTNktTDDyJqgPBQFt672Q76Wf+Ve1DfMl+89yjw8XZ3ZZxTeKiXGXzFKt4K3lk4ZzCbRlO2RzklSMCVe3cor51Qh6oFZL6sU2HLxXB4a4bqRbZR3PpPT/ScRZ2jW8lH93ekCC0zh09Zw0E5GxtbchGGBIAtnE7r4kf8zd3uGZcLGZR9PXXVsNtmTozA==
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
