---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgAiBwdBThcKUGw2dA8lMXfpffFrSYbhRQqia5cBxzqPmiLHU4NaLqOTnEL2m+ZgPdYNWLLyW7pCBmZgTPfkcHyLInLvMO5hd0sZ+rZ2uvKF8qkypBRWNN/SoxSi7IFOttGzFPS+5OlYSc/Bx2GC8JKMWZOvLHBLVM3oCLl+nxditl8OKWZn7N+FtXvVIVKJmjT19DwzZXBlrFgX6sW6MncUXXZlDVnyZpJpfFOW+IFh/hRZQLFq2eA/L4EcXcwOGdSFakO+C9f9cC5Sxyd0l9/lV9OcMWZaNvzUNk/mK889Tw3UDAUSCMK8QbMhdPTK0j9Spcv+RUdlHAbuK6oNR9JxMZFOH9Xrba9j8qgv2Vkillqv5n3R4W4jL6bW/gawv2yk7jvaTx1fixPNkOdGW2pt5XWBJf7R8iR8KkxQzIzpK3t7D9Fal4Ko3Qe6jZ193KFUteAUt0SEl8elcQrjEqEVd14HglbYyyD3+oziqva297vHDHqb4iEPM2FkNnVDxGUnmEFCQCZKuP9uIZZDo6si4PEGreN/rfTVPZjHLj8E0hqHOSOIQwl9kGQ7gfM9o7gnr1g6vZiStYxguNRtcj6C5/6wPi6I+ooQrYBYdV/hFFiwHHpOG4HfyWn+ezK8wC1PbdbYJ8ocI5x1VH7nYAJwhWAha92lcP0fKiHoohzAaxLV52wIYCpJ3GjydL+mhUftxzqjSltn+KCpNL34PiRVfNSghqdNHEffbCVabHQCC3qSjR52F5UnlUMoBSf4ceJTvT6v+sr6b7Oi2uXjvkxwc44I2d4wPvrGrpcfhXuz9yphbJV6DYbJ2pmWAhAfHucEwCRqy50x3VDGi9ocpDeEtkBKokWDFLve5szJpI7axsxGj1TIQZ8w2OjsixAvrLh8cSev9AHzOHyTPfGe18TiQRzmV7E9HHLxoyzZDym5o9bGqwJORBh0shD2Q/IqcGBX/ySX4BNX9YerjCrmU/qLVryA39kJJLOr9tekHaSNBi7HXqW1l8jb17vyx6SdjFyZ+lWte6cmfYV41mCanDWw7qk0S4lx9UvrbKDv93t5OU64Jqeu7jcmlbrMYek9vPjV64VeyRH8YJ+4SFHqSa4q9tr309qs6ZIMghpeELcoSFSg/oLlJiaAidp3Wpfsn0MLOaQ79v9SaPxldJBdg+YI3j0cqw5bq9iNHkZ7vBd8yGXL+LKqBZatvl0MVkKS3B513Y7yn53YqQ+ePQrvoBW9k5mffouHGSchJUWgWO9smuUsq+XQkIXHIH10z8onj1Dm3wp48x9caewnKXzmT8/iyrvXMetJALBb29J6oEaMchYXj7ztsK0IxmSqolBreJNff+hIOYLrUuOZSZjNp9lXfWa3883onlZFwvQlQM9Xk8lK+qH3LaUYPRcrddf1nBlw9iElEYWCmbHVhaCuzswDY5yeIbpkH3Thq0NHgkUs0Rq4RsB0RaSJGUWFYI4h5HA1Sj2YqXkMOJoVtSr0/D9tFQUtYaJqXxiX7a3UfuptU044lk9U7YJxTQHKMXrDjZwmFB06TafNkEiOfoc3XEWyiNJ/71pq8Rxz2ryAICkkKXe4P/pC3M48AqERvlRfSVGYTqsN+HgSDhSppO1kKDmDvfM+l9DmNG6qq3oJLq0lS+ckw0DM0Hec7mImtoM5MNx1E/rXE00q9hHPr5zcDceWmxHNXot1eXxqQlIkGfFmO/vcq/Oa3m0rZShUUq3QEW9EoIU=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
