---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgB2MQh6OVQK6uT8FDT482fqW5EXy47SSIgPDznHcgoinMuMzi8kAQB0+faFRbqxUc7lFWxpdbzVZxIjdRvyy1ccl2eTw4/n0bEn9xm0K98CL7A5S5yh6SBu4boauqAuo/sdEABy7WiQedU/EBFohTuLjMvsIBBLmzaEtW29dzWvf77x9Br01g3yWzY7LrF1L6X8f2T2YKzWA93C56wuW9cLB7SR7o18s3VvLucSTna9jm4veVbVmBqAcm1hixf4BCtHrwITt33SCFTBH77Ndl4Es0X+qTijnalp/HqegJ+TAPNn8QEvKmWjR4Ypsl/R6n/5uR8cawx5o1qSy9NkkGA5WN5toUg2nlm2dgA44o5akq3lA0gzudrQS5AqYDZWQybU51SKQBAfzlNz4TGX77e9RldWDrLhuizlwSs5dfuxaIicCqURH4pB6VhsouR9IoUaYmj7roUJlqgY6g0gdfUllGrkoMMdu7aSXZhyGQuWUu7Ie/DCMplCWm784s166c01RDsz+iKJgkPTxpW50Q5Iq4Ptu2nRfHQWyOxnHcFJglT4odZTLIwdxuKI2MI02mpX6ZlnSNiNGwDkrl0UgnzXtVjj//ee12b37XKAhS03I+IqIG/LLfpKG6XxAR6Lr4q4e4K8oeEhMf+8u4Eyy6VK/6c44P52Pz2AlsvLv5Bzom4q+9SMfa7m7snOWmITfoU8eEi/4n174hFqpsqq40f687SgSC0rW9gxesz3fm4OEAwlfb+yQy+Uzs29jnTIirCtRvHqljUP4THn4Fk4u/hf+GI7jx1bKaVf1oo6SdqzSolX1/3HOyYH7vTEWR1W8auvXancNfCvMP+R5aLeub8OhmtnJxKMyCwm6/f4EVvyPhSd8LHrBapNBTEdDB1fQyqqMrst6k16x3wx8u/x2JkIXecX3Gwn3cCHt0pl05HJvT3wcqhK4EVMCjD6500dy6TTN7tLTr3xwKd6RflKYi8HvRTNhEdcZ23Tkiuf8N8A+CgnIMbEWCmvtUVnojc4dvzTCf6F2YVdT3AtTKhmcXYZaEv/lkZxPFoH79r+ldIHjqPUEGxY8C0IwhV17ffXHRClY3ltoosXHu3vrBCxTA7IhzP2QH/nr1SHiMPvUcrj83oERAagW1ZICZFJMgBBRixCFfQj2vEN0MgidGBSN7XHWcWS4zKPiXaP3DeeGR/agY1pa9K/26XJEZTyXb6xP6CMUfpZB7lySGa3YqlkPUGrsD18ormdqeFmrCIDWbijUkWU2vfC6z8J3kXh7kuxSXTCNylmsP7ObN5Loxgtc51qMCjweP6LlhANwlHc7bXTSt23EaWfQv/M2dHaGcuxtl2u50mZvaarGZDxFVi72/08pax0cJaDX6mS2ZxWKDcGNk2t8qCmioAfnfyEX5/vkAysbSypDMpcU/2OVrawFoedKc9p+KTTSrOld2ITvQ+R4V9gWMe+VjqbTXYpo1W7p8o=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
