---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgBG1LwROMSzXchu2jYi201YjUyZoUrf6AO62PUBQqK+DGtdSpeSveh8POjn7Z+DyrTU7Mut3J+uQE1FoFq/GVMY1fRc7SL3xfnlTblioIOtMVLPCJqLX9mHzq0tldMEMnhZVbwqEWuXp3oVJDK+j+03Q4Qynp2knlhMYnG+hXSeO1cIjZ2ILIUIlaHzsNW2y+j5UvBewQ0Bb6YeTXjJ/g+8SgnmmJc7UukGUgm6WO3sRDh+O30VMVqz/BRVtdCxCNRsYVDhLxHuXY8QrTZ6M1Xml1ubdLnAs9Bzsm6pI3SZSzPcaJsfln8Xe8D8ajhE8FTs9BcG89/k+Mjqd7uGVLc/6Lhk9iM4WOhkHBpp9XpfGL5QkuCMDXTcFLQ8XdDglVDOK5KamGOUFYY3xnNEF4eD28URDEA9Wc8pyszMjhriLfLQggG0v0E4qGAUXDhSn/JUK5QBOYBe8jnzeXI4roSQjUeZ0CrkjpaBK6lFuA9WPTvl47Ymbf8hBXS4OXdrRVp/008/FtaLaKuc7IRaMIuc140mfsYmsB7tysatVobFpVK5MC+yktkR5GibVMG4Vx6xNwHSDHt/MKrBu1dKjp0fWgPVc8Qo6H/BZVmtCtUTvqReGMkMf3emZkRKl7BGg5BprCFipUAsoxNrpl2iS3mCQ6tpM8bHI+0I1fwZ6WtE47lD+gkN3Eia848MYQo/Q348GqISce38tGeu4c0i2LTG5bHpQCzaIvw3tQ8PkWP2wyhJ6RChuhSUY9OkIdWvViGnfwUm2vqla0uUsTHCgOZf97BK8+hu3VU2wrtUM/jVy4SBlnZ8qtkWhBzAvHsYTUcnfWf3jv8Y9y4ie5c5G04+xnikJmxRqFfevyyqtUj/zGQl4aEoGKfLpDL0+fPy5x4zK65s9u2mWHBIXlK5rUm0YV0yQ1+3ycG1C7ksDTHZOvRsicTgdJp6MSVRI8dvpTFIusvSB8gQyBWAk0xiCGn1i1xUGzpNr3eo6qUHeg/DaoYqvGJ0/MxD/e0twobbgw08mayb8n/bAh6Ww+rSIAO/Viklfa/amiHqtBx2lqZw4nTy5OZqs0R56C7m7rHH2QcfIm5D/a0EX0Nsfg/DXbT6jqDwXfp7MIsTmmQ2bDIr8vVrmADte77/Oorl07n9WPCJO7IbXyQ+hNCsInvbWDLKG/ug2PuW1vleU9X38gels6aF/bIw3A8VCNVlWJ/ugejDlufJ+soAiJg0fVEA88ymajqvmikVrxX4QpS/+++XktaGtnxmzrpbqi9cb8RuV426l2IYBgEQPEng0qCSsLCiZXS4DSDoSq61TV+RHOl0mdPXQkuOY3phQP2K/qBtNHJia5DcwqdGWzHgQ9ONPzmVaRtKqHZtz8G5rN1eo1ceFCLmFgKIT1sIa+vXXI9N+ViASA9RnocNQr+5VBb56JQb5Tt3I4rxLVd+FfKG6xpDfV1Cu1aZeLzDDqcP7Pg=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
