---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgA69KD9Dmhw/wVVyO1OVPPWcHq2XL4j2kQecnsvzkQAvgLqv/pXknYmpicBra/MdDFMUOGF5N8VcfGJouOtdLXHKelDgxK3qG32/RLaiuGvJbqYh15MqH1V8eex2S/l4dt2b1oapcj5CX28q82ESyP7LUR1dLxp9TGhCYpkwEFYYg2rr7c4cHWO4UtszCCjej56E0CW9HGtyg0iMb49SG8qLx/Y04f2+2aOKC/Hh+y+n9eXlMCriteyHYjEkn0o4hM+jHvrH7kFGysivHcqmCcq2THPDj2br8GmwliP6ZIGRp3H9Fsk29mA1v2O2e06Rh+QjRkphASkiAKO9JbkOGIcAl3P7KsS/1hfigafPBGHJ7vBvLAtGP1IMwkKilubtUZztSu/9On19ltHkso9F2QtF115kI71tH3GASHi71JWn3M8GOxqoibZxK0BuWKPbjdB3ynwyUTcQTyvezyVipj7H6NSHmnbeY8poJQW35ElASTH18uYgtafAsJKoprL3kA9jgQbrZnYxdO7Xmg/syrnCYr0x3JzytQm0QX6vdIj1/eeE45X88crkHFvVHE8cs2W3dZE8FGdeu8UbZln7Itucm9CtWHsxfQqx7tJnMClJm2NDMNbHGQXhUpMEb5eFJz8y9TM0/Gw2Zeb+uZ2Gb18vaTePOvavxDMJW98dA9411BYA1thEfuOQU5o4i0LN74k4Ckt1YWgZGmtLKdGfKGK6ty0orMJn4nbZUBNDh1/l8XiKR4L+UMH6KfzKFGnXi/NrG54T1fBj4slI4YOdgpRRQT8S4AVg62cEOr4Q9UEKXnZDeDPl3hlax+NANuavgHlSOR3asVSBozadMot4qa6vWYpSSlT0i7KaCWTGiiPmbZtkJWUqXhz2LlrS6+2q3p10aF5kwW05bbc+u+jCmm4jOD/D8cIzUaSz16T6v6lNEeiKkhGqfFlXDVumrpQt2paVU3IFUQQrL7YvZa5eEzkVuDhnNvU0NqhnNqEak4ts3PjRq3O1toh7vLcWf/HzvmLXHcvcjxbg5dKhWtLDbhxDSHTE+iT/NFClLwwoGOszb+hCL+Fo0Ez6DC2nBMOtowNmaRUhMS18Bol3PPCc0u2jUoL241Q/K7QBwRMy5rEDw2XKMyXddv5lX8EbuUAGLyIYmVwuUeVKiL6xVJycKBSBMiikwo5haAK/cqF/g4wew5hWc8/lufD9+K1wjiLUxmQnpgMuhjfDqcHITmJcW+xdRAxAxBGRkHldGz2qd2yuilOz2WZXBI50p6uCLLc/LuVMCbatJxGZLRqtqDVXFIuVKRFWjJ2aH+/BmCA2aqrd3kAbVnmNYV6P3Ip48Ucws2Jbv7MS9Q3H+DuYpW6lQeJ6tA3Uh0a4zDrAX3KNoml8h6P67OrdwqGWwZvSt+KGIs9iCfYKeelhoAk0rFMX6M+jgbSwShIX8/JtJIoyH9eP1ETGzaM4MVBaCpY64jiM7wBSheb8SKvWKI2gSxf1w0lJZqY9t5mzRtC5RjtxfdcSJg=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
