---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgCoXvD+0vovE58n0cCFaOkE1Xo1XoxB2Rht7sCNoLaoaA+yRVf3qaX7aCHpSkRHexRsJKCtZedyFvkR4OsdeVkA+bRjTAs+o8s8UR1rIu7H87wuEVk14YUQja25/4rhW6FfbfL9wfaRiPskiMz55t77KgibpADv4o1zJMbUQtBfMVNqikRQyr/spX4zUZ82aYQdPEBmIbiCspPXcl7WINDXmFkkKRaF6zSwFiape3oPGaelJJAXT2KQizmAkYdnKs633RHit+v5nc9aKGMg3JK5JJVNhJuk2oASkwHH7YCez5ccjq6+rIv7jtSedTqoh5sfZj5JLw9MxDsEMFnKTftS3fRz3Gf51aC+aQsJ5utIJcCtlzmSDeihwiHTjUbFzuchaB3SXmCd5Q4gU4tpQZr8fhEBLTdiG6rgXh+VNyEe/SNQE+kodtaal2NJL5KKPFh6mKak1lBQsDmavx2o/9IF+0kukia4aI6BEVZTWHThfO1w48572GUQWz59U4Ko+Wf4wGpYA9GcI1McAyTAaQmyDOzdnw7t7z/UvpHuu2l5jffqPy+3N5IsduprL+5fgOU1xkBAa3Wg2G8qBH2jTwYHzWSu0hL/q31Z0NIzMHLxft/lX6pq2ZYY8SHngHTJ4Egt7RqWVQvD9YgI/9CX1czAAyRU8qP19P7bmKxfifVVqftAlFyvjCLlZMVIUgB3XDOLNjv1U/zZzuA/95bptHwM9Pp7VUfZHmPLiuTjJ0RjL0PLVy7e79AREXK2DUk1Jjy1G86J2dKCA2z7T1BFR7HZwv4lEx6A8/fDuHwEke6EkdNYaCbBN+A9x0DGnnV9QSqfiuVQcMwjWnvuNW0K+BmRf7BE7olUx9Gi6vAYCII/jdL8Ftv9rja9cECQug9OmyP1vr7LO6kPMCDhjf0Q2sHcZoxF+ea99rJ5go5g0m3d52RWzRK2UKw92tPzWf0+q9F9oJxvJrRPwhflOvr0JgcYMWjw/ePke6QhXk1mC7g69/N1qOp8OiowGAZYpQL/NCavypsD0fpfBq0vzlao84lLL3DyR/enDbPeOLs95VJwgQWyn3QdgCCuYOP6WESfJXvDpL2U9v7qIdRuRhw=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
