---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgCt2JcCCOWdApVOT1g/PszQUaRW8JYqgCKs1gnMaQ+TEcbUGAATn/PaFbAkGK4tzpKWe+dqK2cT0H6WOa9Xl26BkL8lhCofAmZsc+HSXmCZgAg3FVcAWMV/ax+l7b3QQ887DakhZoS3w3vjRoOV1rIfDgFctjHu0gyS074bCKvvnGB2jEJ7i1B5Gva4HKwt+PHCrk3MditLLt8T0vyWVzu7hVyip+g41Kb2BCvg2G6HtDRpmHMgtd072lyRr8hYUW5EwkmpyXUbUw5mVmY4x6JtkX2AMr6T3tVan6SaoYymEC1FeFvS7Ic+7CxtVY1yiBWxOxslfhw+CqP7hhr+X1OZ1n+76zgoz/pyMsDSSjgG1NvrKSkhhGG4xahfg3osi4QZFpvEx7cp+NCcteM+rW25weddTAcjY9oJvhE+2py9vITmKt7amadcUy7OQeHJJsIuXKvdCRle5PBXEBhANJOcxR0e9jTUxKvO6MggI7XGz2SCB4cw4+wMf6nip8KThtAgTob/yvvImDYqrSyd33xpte/MJt6LQ14Z9HS1LQWztszTXRBAyw3dgmtcdbu273WXvv33Eqsv/2fHozC9jBWmUikyhVzLy/Fc1pBB9htS9qU/yiQqrrIttzifFRryxcO1hIxSJHTvWVsozwE9mIRg86p3wDPG++uOeUwih1LLog3KU6qaN71ogERH5yDuSH6rT466qXoOlYEF+PMiRtHicAsTBLOq+IMtGnO6paID46GzRtl5mqXjAlfjXX2QKZ5VDDSU/CS6Y4LZkqMhoTOPw5ki+p4KWSI4OqWilgJUjxmuFNmLaumZbz1FsM6a77+J+qY6wEIJ2y9OvEbwgTMGhB90Vi5kTO4FvSpyPTgD/SuK6ziXVW0xcPJGQi9R4DHFqOY4CFE6a4hn6byQPKVozDBRsSB1vCNk/7bbzoN+3UhzPw5kyftgEZSKrasU2UlZV/6f5bczAF1S6cTpzdtuYSG8/pk57fVkwcC8u2njevEaSQqKTspqR056Dbrh/9EgkONdV3FQrHDpBBmdI4ctaKABgyyONnEIGZd8sM62iSa0zvOmOUvY1Ndpopq7/VNjwkpR8jPQsCgs9R16VGrjZHnCemCcxvU32BRlRVxtxwDD4Y7AbVmOyuX7lCA881nCh/768fFftduZl/uYBKgV7qqAhXYqdTR40V5226mLkTNQyauLxLKFDyl+8Tjk+uT+bWIo5rVmqin5Yr+R4qVDMuHlbz0dRHzQGh5uC0rSFmUv8xIhuxG78Q/ig3JgZGcb1rAy2gvDXJMCS+3MarMGoqjBBlVwqEjaP5pi+Af8czcYQnAYmdqNJQQQXJXdXQWtgOcEPmJoFiuqm5d48rjKCwIpiPEPfLkCF8yt5kIYk5TDWNcJ1wao3EhPIVGUKU8c9MVRM42tu9ldetx0CnxJZzk7yyG37MA/sCJwwxllKLLsi43kb0Ho9mErVHVj6miDafTTt8VQcFzIYoc03IbZou3Gzd+thl/goxkuJJVB
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
