---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgB4I+GS419BcKRMDrDHVsDMlVxnirc0NBPQUgVMihagpzww+c6WZY2ayqVNsUQEmK3mAr4wVetmMhG5tjoJvcdE3FWlE7EkD3TNHWBVQhfM4Zu2VvSc8RKIBFMVNQOBj2XtmmqlCO299gmAC2AM5Rgq6UBlcUYU/Nonh5j/dlVJDVpIMo4tf16H99+tR9y0vNjhutgnFwFpS3Vkf4oYAmC/akJMeVXBoQnJthzybGRBNCyd0ZxRcY+TSgyEhe8y5UNagqtZv5bKHIBvxy+AGjukXNVTzVxupDxKHxUgVeT0hj04hQ9iGN5xGLSya7vTxAn0HgflrR+lsdw3b48/15pj1+D12a8HTr+fbKgTTprvDfDC8x0blIpcEazKPOB5PWNwhg1HC9brlwmDj4Hh6aEShdvB2Vp1pMtJ3N+wdPIAPsL5ADPy+BXDscnzsJNWj48Xz7QBNurtaiqCmdVU2lzRKhnZ+cTCM/kX+jBzDGLnd5L9WHpVbCUJUhqcnzB9vJ/4TIoUeNMVZe3V0awvD4vWS8QbBe84DXsXIXiMRxXkI7GhkcWBLoXtggvVAomldgVU8X2aW5rpNuTTrHY53xLjWONNMCNXvrLhrQvmVg99hTCzgeKkmw6fNxZrQOXKsjifIGL6/BfHHZMxUfvgakQDTLyMxyOUuvji16+kHPg3wkCmQWuw4Ox/n7ljj390yaeqp1tiSQwY26AEKvJxxuLF0TCDYpyk86d8bKDMprUxNlc5OgfeZ0FKauzHP0my/CMlipstUOgKXR9QWYd9XFz6CpLR3JFQ5yQZbeLksxk6U+/bkqH0BZCPy/wsWAJ3MFL6oz0Sebj1ze+7lRjK2wx4QWW59Z6Ndklo1+i7Ximve/7PBGFrJvISrpI1TOLHXwIVW0ERLI8+MGKdW/5RnLVEDd3aChqnAzjjKCKuyn9aPjKlHNW23Hdpo8FrJNhsPv9yqQe+PcEjN9hNbM9SIQMQYJoUktX4Uq8zUMD/3BEJXPtm8gBt2tkVto7Dr2do7pus4UlgCETvycU2rck43WFioDy2uAaGDLzs3N+BMnl2XlIIr8CwJPZx9YDWw7w99ey4rAPLwux8EBPyvxclL+kBEvJtZ4lnD4FwEdtmyV4B9qDOSOlejFEuPbptrXY+qLope5h2SBEq0JnryrRX4U/uvbQPnGXbm4Ujnr7OBZq8A5wjXKAKeD7Q7b16K7IR84YHXBeDqlVCmHqZUZ/jefuIWNT0UvAp+d0l8RXRu9c4YqdgSy6PjYq54M8KDAhUFMSLF0o/0zASrj3kaBNZd0tw3wYHXPPty1yBLcCXzTaeHRM2gtQGDfIozQJNH33tlGWsu6pjgaS5pXZT9Ri/l1Miqxi5Tm3+iONrJBTfrepOqyp6KMphM970cVe6NibuQZ4BGnqyD4UFOHlf5s8ZQr8janp3HrSyPUmJ3kmc32tvQPQS8tCcXPcbc+nbeo2MRXY=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
