---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgBCCjh4cGkjnHSG3zqJXG+Q1EpWoKmHo895NUSC4wnyPgQOl70B3CNaZEK4bXT4JolitiU9bCkHFvkGhDYfWp5hvNKvMJgBbnfsMZ6M+ulp78J4L0MlNFKfHN0+bjDOxQA1rBv1Z300Hopb8yc8ZhPcIm/8hRovIo9OvRAnjCAf8epBGI3PvqCg8dPvthLdLybsQGq2/xAE6CXww3iRm6igHEaJA2HaIXOgcH53lzW8Hczs4o16a79Y5CSEwUVJZXvc4PGqXS4UPgZBUJ3qS9+hvwuXm84I26lEQ2kSIpmBmOoXAqa2sYHETXUthqjWIoLLDwUnpwx5c/uKtnqp5h+kw2SV2lSZS1vXyQGfB7qW2EklzyDAX/cWbfUGb2M8dG69etF/0RcuN9xGZdU3sNNFO737SaxAm2smWJe+9gMkrJnD1+wfG5IpZJqeTA+auDF7KvNjcaDP3ZdKUMeiEK/aMcQ6a3fBlIPO//rTSzjFd4qAepycH1/W5dq3H5W5WmMcKJUM6Tyd2b6SdE+mkxCjsdqCqhXlvCSQeJIWARxkaX65J0bb1rI3K6T/BKIEwUOoyepYIkTB7M19/tifJT0Y99K7PC7kWHoJ8ybKGBtIUC2OJoBQ5Mh4ZVd8Mdtl0ilkgW4myehfLyxvR7kW7p5+rDgLvDJviSSOqdgU19er83sSGTOIQ29/rOWbWjh7qssMfgEn6hSfmXDUqF7Q66KB9BrUTwkN2LaLMwa6HDc9ea6/FdFZAFmPhdsQ+z8/cP8mIzLHv3cNwhOqiS5QK/VQlnNAhFfOx8HqcqLezy7ZWrd7YPzKifWDJKw49hMGnXRP9yYc6+TQikadiASz4P5gIZHNUrVEoyeWsXdnE33MvDBfYFs9mOD2IvkuS/oRtpzKpbqV+YDtt9zA6uwLm0QFcGjcx7rzty54xwkh5wFzZ3nmP1FVcRgn3RQIrOvzdezeqPwo+V+0JjI1tDd0gfwFc6e/hKTSoHUC1iD+X+L1vtAIJ5swUooVLCUJaYHDzzJUGYT6EJkJN0JJqQzP3aKNCbkwcVJa1mu1dIpomVIiSbzWe1j9IpxdUkWMa1KqN2KE47WL88v50vUglAWvDg4kC61SP+ZXIbTJoRfVtvLGTAiCvXVA4UhhBZD3Gt6LbFE2W9n5BRBGvT/ZO1qtY/DmV7SOUBzUjxFUB7xICKKWTPoabb1RwSB0W3XvUof90q4MdjNQKmiM/LqjSCvY2X7IObeghhD/30aD9dSunT2G6+9xugcIzi6qVKMci/Na+gpKV7yFt4xPY7lEyhwd0aoWZpemqlBVC0dMJRfdujp6hoeC6tgQ9T772Yh6MYEBGuWOBJP17+I0+26H2HEiNZnDQygocGthNpjnQ+SKd9tExvLzfu6bPn8FuBZZmaxtUOKngQOycJSSB2GqcV0x4WpDnVE/9Q3vQs2t93GFeJ/DYEMqjaGD9J6MV6nvuyuMJgMBmxh0GKvn9ZkSbazXbXsCRK27ubmZ8bggpQ7qQpmo0RNgxxpdG3hZ8k06nn1HN1e33mH5ANm1ew+rGK2qRu8F
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
