---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgBbtXkXf0KzrWvrFQFmChUAVCpCWUNSmCQPIxJ6h4wRMp1SrSESMLEFQBEs8HxVQ583fG1iTiHsJEu9xYamZfoIYOSZTG7/ihc5XqIVJKFgWrBBraEpe/kb7cjRyQyqmQK/jU9Boul95tFr+EIQMl9E+NWa0lj7wJhyFNF7lfBz1fnDCl7JXeSTRF4xppHcrWbORGlhwidNbYr0Zyb52P0NFdeB5OSfhe+6Y5ZxyC9lqsv75HKudc6jy0s61/XozEQNl7oO0MHaOnMECXnVugftSrX4K4ibVDYldeMGv4oz1SScto1whRkyDtKl9kBf/0Ox3ag7cdNkvVEcMj5asCMu7hBsGe9CuXzDTLSjWtxuPOW6DDK4opGutcQl583cuZs6fYjIOpGCwt+aEkAqncKyHlUrWLOBiw5ACyhie3tcNBwgNQh6PtliobeLCfHi2IMhg63H03bI3ZTnwYnpu8w+uZ9S7ieKsK0AmBmSlHI5CkUh//IdiqXFJefiy4Zzk9oUj7esFhn57SrCMjPLVc8cN4fBDM4S9Pd2n2DCSm5ALkY1VtyIq3rLFuxFns6zMYLU4hfqbyqj+dgLvrekrUaD0ohIMTHZBx+HkzhRcqKN27AzjCSVfDnHYHdn6bgT45VzYaIqA9A6rZJNG8lQLZl1e1+xh+O/MvfBWuYQ98fTAG53GYNZC6Ct6eExlUuGGqu2gKuO9ZhJ9ZtA5JyHzBauxPY7nh3+A6Wi5JOg8hjShlVWVYJNWe0t6XDO/KfOBBBrlLFkv8G+UBb42y9FILFhgTiDcEV/PAyY2zyoq8/FExGDs7vZuaXbpdpApR50pei/nXAvfzyw50m2xyjwoRDiS3G3zvBaOUm9VLy2CUjuXf3TSZhpMVgIt4RW2Cwm/mXMgk47GgMmR2wDBaMkWBp11yaSE5CwdP3VqpMt14HYAcxYqCXTsWi11IQDHkLO+i21XreH6Kn3lukSNkwE1EGCloNJQPmR0q2F0gSODNOw4bxtpwTdrvcbLyNbn2S9i7pu1z/WBttWXgg+GA/Z1GFet+IAD/R/HcfhzcdjB685xbgF92HzoH/ZqS4IYLS1aAk2eIP0+iG7+rNObJA5Nq64TQuWXQJlKwYospjDu9eG49+c3/ZR7PjcOYAPVoErBxRiG8FVc0CxVg==
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
