---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgA/Ol42iB2L9pui4tuCE4xcKqsifqHrZwMb29SSW/bDrVEM6xOhlJEinZY1w+6Cp/9qQ+CrasuaP58s+93T55Dq3WsTaJvRFd6etQDNG7IVJDfA5E7VyUUamY5mEVHWUrq8D+Cx0SSIVGXCVIFepc9iKVTwVvOfkulST2OQJFrD2AdIGlPHAY3x5pq6EE1qpzuuNK5ce+4NlC+9gWo7PCzZXFfJ9TJeJxohuuYS3o0+oj4fJUy3d+0VhBsfJdgjpz2vzX9SEFNgnFANzFZWCtJa30dn2YSjY2dz5PU117sKVYySeBkjgoNMiP7/imbZ155YtIGYuweVDgzq8fixFpjPUbOj9auIQUDmUiWL/5Xz06XYb32VIPIQtSbUyAjAvnWpMUmyaCnYs7vKnMNdcbC0a2CAnNL6O0bdKGvBm4X3kupoRYRpJR+EmuXAMyckMn78Ffb1luBvF2lXhbyqvqD8FY8f8DzFSAiLtBJwQtmeErpOJUdkT4pO9ruvbuL3IC1/yEoEbVmvSm8XUlDQgF0ltFHboLRHfdQZPxHUnsiXoW5L6y5qMsEgvtG2l4Fz7Q2MyR2eKOvDlipo+X3mgvhupjLnrVe3tNcD9fPBj4+XzK74/F+AnE6RErIrfs7osqORp/szn7Zg1CNa4uJEX4Yn9ToS9860/6HI519Oe7ZJ/sPyL9UP196+THdB/sSDPXjwxYKgv3D0J1zjj0XGNlAy2YAHEqw9RLimb0DRbwfjMEJzxppPP3M9OxWokysq+felSRCpC4uj1NT5ysMLkL+uQHzOnZci9zemSmjnqaKf8EqLpG37z8El6ydipKpVpQG+aNEzD2HuQfDwOByoE3jOMwBl66wJ4Tl7u1cNdm+1Y7pMmQxhYx/kga2Smx3SsyyKCBFePVk+zSBqKS+qgw0V9ZALAbK4PojecgmkXEq/fNqXyhAoJdxBSZcYuW4KMEdfgKH/rpd+Z3gv8pX2akoH5G/g+RSWEYi3J1gxFYgcNJlN/UgSnbALStZYV0Lj06AC5yWWt94EcpCkrMU0+EIOlmlBJ6S+/XeQ+OjAvuJ7J3GYyRdjIWVXUqUgenY5i/95FkfL74mrCFs5bHpgM4r4hK3K7FcuiIXjWCfe66gPcHrU/8MC76wk/fU1SoXLY1rv3fG0mt8vLILzyrjMyDh0jwfVcAnKILp8k97of/ZRH5j9xe514BoK45Be5CVoYD39itbSVgNCi2iXD0/jsWjq5QUZ7oOFejad7hxEj2uJClCfKYQm1E+YtlvGzM0Deb5XQUviEcN6n5RM9gYW+x7CVylP1a8JzTeflGIxvQgLZoxCzs2WTgQXWOpZ5BHeX4aUZj3lQGyKNNLgIIBClK3V4BEdCVO8Mv51rEg9fXk3Qs231lOir4Y59sD6SEEO6D0hFJf9jRq5MF+HJQSuF8/XEecfa4LduBkNXSXyYP0E0Tr6Sh1YAJXlO7mxAiieVwOPhiiX5NgXUut175zVh7a171db5Fbne/jjKtRI3sIzLjwJITztJWC3MPamUcQuVeI7asumeb08hzO5F58Boezk3JeDwU+icWfLFhomvRkJw+UmZni3eflcbZUC/3ldwQAShBrOKpY33emqMwIuSZut0LLZpdsE3lc0KV/dtxw76EjgBw8L83GGzm0qoE0ejPHmeMBohzR9
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
