---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: homecloud
spec:
  encryptedData:
    config: AgA42YXRYbT92w1l82w9Ye/Ly05rMv8Q832eKx7OU6srAj1JFp3JgVy+JcJOP8o3OnV0yxfijHy+MaB+9ohXk1w2s97heHFMMlb4dhAjo1VZJkpHcYyVmpT6Hd5Oc1n4ShNK+uHm+Mdj2OV07Mz2AttehpKm3s7RYU2LUG9GFx+5d8J2hryj3AGF63TbT7mZbxkEexDNIBoVzwm7LQfJ4ay38tkSLNWjEnDYYOkgkgR+RrbNK9plXkbt7Mi2pK3gQPWNqM3k3SgTYDKhvj0XEH7OCSB9UicdAT8Vx39V6cJNrSXsFqSouidX4ir2m9wWfBV9OPnEebNlETGPAtqzn3fHDcsTWUMS5+ECGkDt8RUazn6/Wgb9Fv4H3M1TGsYtxhGdUBTBua/Vh6R9Hq2UVTbnOTsWel/5vy/4kBMZjglvQkIsNwLhKDYE4Rnnk5y4tUj6qm/HcrdDeEBjRg9VBM2gcd7pK7RhHXJuNpa6RZnDW6N5setwh0lSHaRNE11OdwCiHK50PUH4VsQEoLVqyUiZKlBhPQjqNOqXHWjPTYK3j5iE7BizUaJboDANq7DT5r7UqFXUFjK2oUMA2XQ+GfBnArn38EESnABE8AzNiVY6oWYKbb4Fyn+EMcbdZNxiiINxRu5kAE7x/bsZhKswFljw0wJgOi4dJDyTTduqmMNPeiSYvnIL+eFmYEE8w/s25d0AaXM7+pRaPKbZtf8v2daqzhjDXxPiBu5rSTAEsQjoffxoU9l6Nv1pWK1AAwHaWG+S8IJ/blmshIO+EpZNyuJLt1yLCQv2vod5hplsAIln6rJz/EtySG7+XhXxlAzprHAqdy+ifF2I+Zhqyklz4U5eUvkTl6Kb71eNWOpKdJjRhWgoqIijaTbQXX+kNpKOJ5kTOU0/zUjlad966WzTs0ZrA1jjh6CFQgwPcURzsaFFK+O97mQ321hDnliZS1g4jsmt6Ojeoms9KZaKUgbs2dTxKu/HVf3XNtsQV1y9tY6fwdhDja1BVCwFBPPlG+gBfI4QGp0qpMvL04EN3hFoGeg3s9lbrY8evI/5SeBjMaKsPVsMgODB3wmV4ijdo1wWr30hKgBqHu41RL9yH2Zb9FU/zxU4tqFK
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: homecloud
    type: Opaque
