---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-config
  namespace: vpn
spec:
  encryptedData:
    config: AgAUq7RjAi9if7tBpBt/jCUi113vS3m7KJel3wFjLl4hnC+J7VKLNFFt3RGt5V9r887nP2oNHFtHqTLP1hsIQYCDIeWicsLTUMc9jUckoYkmH9+ZxVhaogsyul3kLsADPusNIoWnFbuSzflRq9t29Ag/kjacjdv8cYjtU5lRo9v0tv4f4pN4zrFZD0DgmWpVcwUsmg60lkiKhDDDEo393reiccDcQ87ejUFymZmNLCuO/Ka5RsDvlp5w3f4YKm1B4aS9twgcLz8xsQRttZk+svvAuNluI5aO0ljg7znIVNf+QNmN+fybvM5lsVCFKqrmhtSZ45QxGgt7ykqnKHBPc9LfAMdW+H833Z0R8a1HEZctJfEx2BANkkYR1r1vvWVaC9JV60IGy2TUDAz9XRPC/1zSBP7rd+jnfoBRjjAX5huZs9uPj7i5vV5vpN5H7LYgwWApFYBZAJfjhzjtFkYq3I6afVUySUy7CdM3LkCDSTEAuLyAPJqjUzttJyGAqBSdptkfuxSYWckY04bOnmNxrwnVAnsZZdV0INv1OluXsRXJHm4zyghf0Ps5hKTf3rX+LGDSNBaPMIujvFXw+F19yCGqU9qenNlz64G38jFNMbAORrWVwRxsVe7G8fBJ5KpIUQbRzK9CXXLNheWg8PdBpHCmzFyAOpQ3DQZxHGL+2eu3mfvJC2gw0usQxUHqjOcPIpHh5ykxUsDw5Oq186fUSQwtkgy0YMVf/qWbnAtvimGxEBBuFK4xNPOnClSHEx90iNzO4Q/MQpwMUiiuStX+7r27jEm48JtsZj4RpazTjWaHJvouPuEaeSPZinClXx/vkpRS2XXlAyOc+U0WTFGzkUGvDlce6xWnSDZTax/PXQ9NE7lqKynrei94hm5vin1mlQhmMiANkU1NGtOrNqtWZIgGooPlyH3exqL20q4SFOMIcmYI3s2TwMKp3wzce+U+0HpJ/jImkpf/5zpMq9Y7QxUJ1fp57wtuXC74tarjDOKx7/u3Y/yO47B1QvK2pZBkqMlm8qWvYuCCp1MbGDYz+nROwyYNTUvjgJeZDMNWVrTjhVvmt8Q3Q/1+WMpxuPCYZy1d/v3kg+N674O1lioYvquEKGJ/Gu1A4Ao2gqFE8n/fr35RVSi2+ZRbPQvDWXf93nvcMLat35njqOxDvVyQLkJhebYkNaJwlysx5xsVn60y5x0EVs6nAqO1sDhwqY6GMfb4JJbApGy9DZkfXoTB1qNP2l0RxQaCcG0LBaA69maLjKHMQSggTtcjeG/QoC9IBkfOXhLWDDHOeA2JsN+vnw8LTAohk/82R4k48fA1+EkDJJbGmiP3FWoS5UToHgyUWdTIIAYZoRAwEjMD6zoWUhmVIOpKIy9FWJnRsiV8+1QdEjdMkdSDlNIfaGw9db5A6in7ffirZAM9npODpD8K5+TJ9QjYFeQUHld3+VdUkD2LQE7SxQm5jTjxurllgc/Ub4hWzBC5mR+8suNiGtZKJtsOtdkYKURLPEEau6g3MS4r
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-config
      namespace: vpn
    type: Opaque
