apiVersion: v1
kind: Service
metadata:
  name: wireguard-homecloud
  namespace: vpn
spec:
  selector:
    app: wireguard-homecloud
  ports:
    - port: 51820
      protocol: UDP
      targetPort: 51820
