apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.lffl.internal`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
  tls:
    secretName: kube-system/self-signed-cert
