apiVersion: v1
kind: Service
metadata:
  name: vectordb
  namespace: librechat
spec:
  selector:
    app: vectordb
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  clusterIP: None
