apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat-api
  namespace: librechat
  labels:
    app: librechat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat-api
  template:
    metadata:
      labels:
        app: librechat-api
    spec:
      containers:
        - name: librechat-api
          image: ghcr.io/danny-avila/librechat-dev-api:latest
          ports:
            - containerPort: 3080
          resources: {}
          envFrom:
            - secretRef:
                name: librechat-env
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongodb.librechat.svc.cluster.local:27017/LibreChat"
            - name: MEILI_HOST
              value: "http://meilisearch.librechat.svc.cluster.local:7700"
            - name: RAG_API_URL
              value: "http://rag-api.librechat.svc.cluster.local:8000"
          volumeMounts:
            - name: config-volume
              mountPath: /app/librechat.yaml
              subPath: librechat.yaml
            - name: images-volume
              mountPath: /app/client/public/images
            - name: uploads-volume
              mountPath: /app/uploads
            - name: logs-volume
              mountPath: /app/api/logs
            # MCP
            - name: webdav-obsidian
              mountPath: /home/user/librechat/obsidian
            - name: webdav-files
              mountPath: /home/user/librechat/files
        - name: webdav-sync-obsidian
          image: owncloud/ocis-sync:latest
          volumeMounts:
            - name: webdav-obsidian
              mountPath: /shared-webdav
          resources: {}
          env:
            - name: WEBDAV_URL
              value: "https://nextcloud.internal.loeffelmeister.de/remote.php/dav/files/loeffel/obsidian/"
            - name: WEBDAV_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webdav-config
                  key: username
            - name: WEBDAV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webdav-config
                  key: password
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "ocis-sync --local-dir /shared-webdav --remote-url $WEBDAV_URL --username $WEBDAV_USERNAME --password $WEBDAV_PASSWORD",
            ]
        - name: webdav-sync-files
          image: owncloud/ocis-sync:latest
          volumeMounts:
            - name: webdav-files
              mountPath: /shared-webdav
          resources: {}
          env:
            - name: WEBDAV_URL
              value: "https://nextcloud.internal.loeffelmeister.de/remote.php/dav/files/loeffel/librechat/files"
            - name: WEBDAV_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webdav-config
                  key: username
            - name: WEBDAV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webdav-config
                  key: password
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "ocis-sync --local-dir /shared-webdav --remote-url $WEBDAV_URL --username $WEBDAV_USERNAME --password $WEBDAV_PASSWORD",
            ]
      volumes:
        - name: config-volume
          configMap:
            name: librechat-config
            items:
              - key: librechat.yaml
                path: librechat.yaml
        - name: images-volume
          persistentVolumeClaim:
            claimName: librechat-images
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: librechat-uploads
        - name: logs-volume
          persistentVolumeClaim:
            claimName: librechat-logs
        - name: webdav-obsidian
          emptyDir: {}
        - name: webdav-files
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: librechat-api
  namespace: librechat
spec:
  selector:
    app: librechat-api
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
  type: ClusterIP
