apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librechat-ingress
  namespace: librechat
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`chat.internal.loeffelmeister.de`) && PathPrefix(`/api/`)
      kind: Rule
      services:
        - name: librechat-api
          port: 3080
          scheme: http
    - match: Host(`chat.internal.loeffelmeister.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: librechat-api
          port: 3080
          scheme: http
