---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: webdav-mount-config
  namespace: librechat
spec:
  encryptedData:
    mounts.json: AgBulnxzXbcMECCXwQHXS6s6zfDah+Ew1uFQ+b/0Qn/N8A4De4SuThYoR2CpdcqNdh8NtPXPsjnB8ekhYHU3OSqRxW717XWl3evLuA6ortOeLH7aiJl7Z7aKasMmM93yQ3b4MfGuzp1fj2+YPFteOsEznmPLUyTMVudqdE6sn0lToj/mIhb5IePDeYmWGCFnrTfpkgMWNSIohJ7DKAXB99Me9pQQCW/Cbm26gYHoWQR3z6rBWzXF2XaiNUGnjQtbirdvW4o27Nrwp6fSMu0XQB7WMG/RNSWZP5FpqtGYO3LiB7KP2t05SW0wcSTWIjFkqy+kGFhHq2vSVc61hrtEzbvXzz+IuU/RV16lNyvI61M/N2G7IcC3H2soeAV2NLd7JMEhRF9EYZKKEFSa1ZwYKLXmZzkeNaePKqC72DITBHqhyfGxTtqAzloRQvmbDVK+8AzxFG0KkBj6ReV/DzlsN08eo7wfTPjAIu2c+6ykrbrUaa3R9KMZidMohwVa+cS58CePvqOMd34ICJS+HAfh99WquAw7+nGV+N5RmPc4rTLOX7+wQ3FX8tU4Z3+YwVvO2mwy8OXvPgRXcXOfHpzaZj3QPQj8zRziz3bOP77/I+pQ22Mr+0BniZo3cPOouKgzMLcpmlZ2bjvdQynBx0AX818B+4hqgL13FERLE1I50Ix3utRGhyXtqxZusvM87LJqhAnRS336ozItox6Bbtb6rY9ovDXhGDmva7Rj8lBiRYEtW4qOZRpqiElP0oAhXxvBHulrLTfSogD/zC54MquXHuWnu8hU2/69QPB6in0/wPTJYQkWYA7cj15Pz6iSAlXkgjrp50/+YIaiVIQJ2CxL3Am7XwHMys9WRH0JB9CPuM1u9pZMIRutl3mm3spVfZsxgA+duTjuoLgdgpchV7KwdjlAhkoJ5onWPYwjSkD18SpJlNv35/fDLYccjZIxCXvvyqecGBLp+ICqo+v+gt1NlLu7x5qOrwvRqufqSM9QXyichX3SdykehEBqA87WmcYaEhvjSFH61uuGG/x89x4nWFb6tphtte54sULCskz3tSNYu778JIOSqEaz8293Rp5mQ3Cn3Ghps7kLZGgsH1h71ukFq+B05zBoAaot0ht6UICzWC0c3Jyz60+wnw0wJzw9jLTSc0K61n7CoC/pjZg+ooD7F5Rx3D1SVRK9ZY1KJbuV1oW7py0ewyB36rZLh8V9gvqdD/fP79sHER9rcVZkmwETtwdhl0PtwKUjsSheMbP1W0DO4tzSrhtcvBt3LXBQLZuEoSOSQ+93WOaxgcxlCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/scope: cluster-wide
      creationTimestamp: null
      name: webdav-mount-config
      namespace: librechat
    type: Opaque
