apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - keycloak/ingress.yaml
  - config/configmap.yaml
  - config/secrets.yaml
