apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.lffl.internal`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
  tls:
    secretName: kube-system/self-signed-cert
