services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    expose:
      - "21115"
      - "21116/tcp"
      - "21116/udp"
    labels:
      - "traefik.enable=true"
      # TCP NAT test
      - "traefik.tcp.routers.rdsk-nat.rule=HostSNI(`rdsk.loeffelmeister.de`)"
      - "traefik.tcp.routers.rdsk-nat.entrypoints=21115"
      - "traefik.tcp.routers.rdsk-nat.service=rdsk-nat"
      - "traefik.tcp.services.rdsk-nat.loadbalancer.server.port=21115"
      # TCP connection
      - "traefik.tcp.routers.rdsk-conn-tcp.rule=HostSNI(`rdsk.loeffelmeister.de`)"
      - "traefik.tcp.routers.rdsk-conn-tcp.entrypoints=21116-tcp"
      - "traefik.tcp.routers.rdsk-conn-tcp.service=rdsk-conn-tcp"
      - "traefik.tcp.services.rdsk-conn-tcp.loadbalancer.server.port=21116"
      # UDP registration/heartbeat
      - "traefik.udp.routers.rdsk-conn-udp.entrypoints=21116-udp"
      - "traefik.udp.routers.rdsk-conn-udp.service=rdsk-conn-udp"
      - "traefik.udp.services.rdsk-conn-udp.loadbalancer.server.port=21116"
    depends_on:
      - hbbr
    restart: unless-stopped
    networks:
      - web

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    expose:
      - "21117"
    labels:
      - "traefik.enable=true"
      # TCP relay
      - "traefik.tcp.routers.rdsk-relay.rule=HostSNI(`rdsk.loeffelmeister.de`)"
      - "traefik.tcp.routers.rdsk-relay.entrypoints=21117"
      - "traefik.tcp.routers.rdsk-relay.service=rdsk-relay"
      - "traefik.tcp.services.rdsk-relay.loadbalancer.server.port=21117"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
