apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcp-context-forge
  namespace: mcp-context-forge
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/mcp-stack
      sourceRef:
        kind: GitRepository
        name: mcp-context-forge
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: mcp-context-forge-values
      valuesKey: values.yaml
