apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: github-arc-system
  namespace: github-arc-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts/
  ref:
    tag: latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: github-arc-runner
  namespace: github-arc-runner
spec:
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts/
  ref:
    tag: latest
