apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github-arc-system-repo
  namespace: github-arc-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts/
  ref:
    tag: latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github-arc-runner-repo
  namespace: github-arc-runner
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts/
  ref:
    tag: latest
