---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgCi54vTyxnlAxuEfKvmK9jqw1s68TDjpiFPvuaWT/2P5zOAYc9AF52eWaNsPVlDaDaUnau9aOyJ/4KXiSfZReF7KPQTm0LcH3eavKK2L1hC59BWEfXku3/H0yKN5EhmABiEQNxbUjevKInxUcXYNb+yOBZ88gv42lZCjRuBfWO9Uc85U/WivTv/Vbwu6he3EsAOobCSwwdH0fkRoUo+mLr1WXOx+VWlHqv9JXKk0hE65nR9bRBbgwzlGebhETWGwvTvOiVhrRg7m+bAsy0w7jKe2tvrET7cmwLUBLdP4U9OC/z6zwanX6BsDnp0d+q8DDnQZy56T/TTOKaLIaiQ52fqbdwoQGSXLESLkoama9+FX4uDWWX2i/2S5ywH+0us5qt159Kxvt6iDSZf7JKhb0H1O0tUKpo49TNpMh4kKxalzNl4qCJbn66xW1+nSXeO/dJrmyqMHWbgSa79HEluWyIZiGhgjiob/Zvzdj9zOtf0MPaYgdIzjjSr9E4yBO+gbrNtnr5Q/tgMCzGMF4E0NikqBg7DimwDm0t8z+o0V9yQfNGIgg6FbSFGbzWMfahD9Tdu5TM4r9w4O9p+L0bAQZPk1/DoLJ+owiolKSVz8FULZXtO5GThIt98flm5MSI6AMMWa/rrh4tdjhTw1r5ljJKhDEdXvOAiV36HifTlIlpWImdeGuRSjmQVJ5mmaF8A3h+pbZjHc8yaKlen5J+4zA==
    nextcloud-username: AgCbOncN7NHWrXWvp+5NuFVuhf+ipeUj9U+CzYZwBsYLskS++Jtj0DuoW0ec8XIuMhu13drKpX8jnJvRfrnHMRWgwE7GHNQ8qxakdmu2Z24FfBAgPCaXf5poj+dcYwkxZSlBBVXVceffAU/1wZy2nGWrfNXc5/1dcSEyu0j2cOtMq1O3yJsE/OPFFawRwulxZYMFx+yWB+UPfx5C3ynOVouIoXuFZRt127UoMKcVOAN71vSPywni5N3u5OqUc81QmJVXYv6ke5EsFx2OrY7SF3gqoQ6et9T7ym2KUWnLupGtaUf0OlTCyn6sqSyESZufQDvy0n7Djr0/EMQqMRPfG9edcC+iR6i9egZX9CAo/hdPphZCmsHRvbslW6+g7zz2FOBROBhpVr0xQH82Qpk9/bZ1wMUlAZnIiCVk7H2KJvoEHyA/dMCxhFfAlfR8Gql2MJhsqdt/KYjJmM4MfYlEbB+olD3PpXRECre2HrC+up9vcvT6Mk5XsDHcjMfEZL/Gwn/TfAMHwWNcTkfrM5qDMFCwid/rgiNlpNYvBNqUkczWr0Ubhw+59ES3wltsSWkawMFTj85fy/HnZNz9uEtqhOM5HEyJdX5ETHM9s8FFchIPul1Kl5T47bQWfP6e2doVYsDSt0gs+juPZx69vAwbgvq+MF3esHTgD2WjU890KfuPy/TjdtACxIH7yyWRRTOwHU4trZk/4R7b
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud
    type: Opaque
