# Configuration for the Wireguard VPN

http:
  routers:
    internal:
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.internal.loeffelmeister.de`) || Host(`internal.loeffelmeister.de`)"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
        domains:
          - main: internal.loeffelmeister.de
            sans:
              - "*.internal.loeffelmeister.de"
      priority: 100
      service: internal

    otherloeffelmeister:
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.loeffelmeister.de`) || Host(`loeffelmeister.de`) || HostRegexp(`{subdomain:[a-z0-9-]+}.lffl.me`) || Host(`lffl.me`)"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
        domains:
          - main: loeffelmeister.de
            sans:
              - "*.loeffelmeister.de"
          - main: lffl.me
            sans:
              - "*.lffl.me"
      priority: 10
      service: otherloeffelmeister

  services:
    internal:
      loadBalancer:
        servers:
          - url: "http://192.168.0.178:80"
          - url: "http://192.168.0.177:80"

    otherloeffelmeister:
      loadBalancer:
        servers:
          - url: "http://192.168.0.178:80"
          - url: "http://192.168.0.177:80"
