# forward port 6443

# Configuration for the Wireguard VPN
tcp:
  routers:
    k3s:
      rule: "HostSNI(`k3s.internal.loeffelmeister.de`)"
      entryPoints:
        - websecure
      service: k3s
      tls:
        passthrough: true

  services:
    k3s:
      loadBalancer:
        servers:
          - address: "10.42.0.1:6443"
