# forward port 6443

# Configuration for the Wireguard VPN
tcp:
  routers:
    k3s:
      rule: "HostSNI(`k3s.internal.loeffelmeister.de`)"
      entryPoints:
        - websecure
      service: k3s
      tls:
        passthrough: true

  services:
    k3s:
      loadBalancer:
        servers:
          - address: "https://192.168.0.177:6443"
