# forward port 6443

# Configuration for the Wireguard VPN
tcp:
  routers:
    k3s:
      rule: "HostSNI(`k3s.internal.loeffelmeister.de`)"
      entryPoints:
        - websecure
      service: k3s
      tls:
        passthrough: true

  services:
    k3s:
      loadBalancer:
        servers:
          - url: "http://10.13.13.2:6443"
http:
  routers:
    otherloeffelmeister:
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.loeffelmeister.de`) || Host(`loeffelmeister.de`) || HostRegexp(`{subdomain:[a-z0-9-]+}.lffl.me`) || Host(`lffl.me`)"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
        domains:
          - main: loeffelmeister.de
            sans:
              - "*.loeffelmeister.de"
          - main: lffl.me
            sans:
              - "*.lffl.me"
      priority: 10
      service: otherloeffelmeister

  services:
    internal:
      loadBalancer:
        servers:
          - url: "http://10.13.13.2:80"

    otherloeffelmeister:
      loadBalancer:
        servers:
          - url: "http://10.13.13.2:80"
