# forward port 6443

# Configuration for the Wireguard VPN
tcp:
  routers:
    k3s:
      rule: "HostSNI(`k3s.internal.loeffelmeister.de`)"
      entryPoints:
        - websecure
      service: k3s
      priority: 999
      tls:
        passthrough: true

  services:
    k3s:
      loadBalancer:
        servers:
          - address: "http://10.13.13.2:6443"
