apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - "10.42.0.0/16"
            - "10.13.13.0/24"
      websecure:
        forwardedHeaders:
          trustedIPs:
            - "10.42.0.0/16"
            - "10.13.13.0/24"
      smb:
        port: 445
        expose:
          defualt: true
        exposedPort: 445
        protocol: TCP
    providers:
      kubernetesCRD:
         allowCrossNamespace: true
    additionalArguments:
      - "--entryPoints.smb.address=:445/tcp"
---
