apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubetail
  namespace: kubetail
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kubetail.loeffelmeister.de`)
      kind: Rule
      services:
        - name: kubetail-dashboard
          port: 8080
      middlewares:
        - name: keycloak-forward-auth
          namespace: forward-auth
    - match: Host(`kubetail.loeffelmeister.de`) && Path(`/graphql`)
      kind: Rule
      services:
        - name: kubetail-cluster-api
          port: 8080
      middlewares:
        - name: forward-auth-proto-https
          namespace: forward-auth
