apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubetail
  namespace: kubetail
spec:
  interval: 5m
  chart:
    spec:
      chart: kubetail
      version: "5.8.36"
      sourceRef:
        kind: HelmRepository
        name: kubetail
        namespace: kubetail
  values: {}
