apiVersion: v1
kind: Service
metadata:
  name: flaresolver
  namespace: media
spec:
  ports:
    - port: 8191
      targetPort: 8191
      name: proxy
    - port: 8192
      targetPort: 8192
      name: prometheus
  selector:
    app: flaresolver
