apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homecloud
resources:
  # disabled because isp does not allow port forwarding :(
  # - ./services/dyndns/
  - ./services/test
