apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # disabled because isp does not allow port forwarding :(
  # - ./services/dyndns/
  - ./ingress
  - ./services/forward-auth
  - ./services/registry
  - ./services/vpn
  - ./services/paperless
  - ./services/keycloak
  - ./services/librechat
  - ./services/searxng
  # - ./services/couchdb
  - ./services/ldap
  - ./services/cyberchef
  - ./services/media
