apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # disabled because isp does not allow port forwarding :(
  # - ./services/dyndns/
  - ingress-config.yml
  - ./services/forward-auth
  - ./services/registry
  - ./services/vpn
  - ./services/paperless
  - ./services/keycloak
  - ./services/librechat
  # - ./services/cheater
  - ./services/searxng
  - ./services/photo-upload
  - ./services/fdroid
  - ./services/couchdb
