apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # disabled because isp does not allow port forwarding :(
  # - ./services/dyndns/
  - ./services/vpn
  - ./services/test
  - ./services/paperless
