services:
  traefik:
    image: traefik:v2.5
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    environment:
      - "CF_API_EMAIL=kraetschmerni@gmail.com"
      - "CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}"
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565"
      - "21115:21115"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21117:21117"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
      - "./config/traefik.yml:/etc/traefik/traefik.yaml"
      - "./config/dynamic:/etc/traefik/dynamic"
    networks:
      - web
      - wg-easy_wg

networks:
  web:
    external: true
  wg-easy_wg:
    external: true
