apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: organizr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`organizr.lffl.internal`)
      kind: Rule
      services:
        - name: organizr
          port: 80
