volumes:
  etc_wireguard:

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      web: {}
      wg:
        ipv4_address: 10.42.42.44
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      ServerIP: 10.13.13.50
    volumes:
      - pihole_data:/etc/pihole
      - ./dns_masq:/etc/dnsmasq.d
    restart: unless-stopped
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    entrypoint: ["/entrypoint.sh"]
    networks:
      web: {}
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - "./entrypoint.sh:/entrypoint.sh:roes"
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.rule=Host(`wg-easy.loeffelmeister.de`)"
      - "traefik.http.routers.wg-easy.entrypoints=websecure"
      - "traefik.http.routers.wg-easy.service=wg-easy"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"
networks:
  web:
    external: true
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
